import * as stylex from "@stylexjs/stylex";

export const markdownStyles = stylex.create({
  blockquote: {
    borderInlineStartColor: "var(--color-line)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: "2px",
    color: "var(--color-ink-muted)",
    marginBottom: "0.5rem",
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.5rem",
    overflowWrap: "normal",
    paddingInlineStart: "0.75rem",
  },
  codeBlock: {
    fontFamily: "var(--font-mono)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
  },
  codeInline: {
    backgroundColor: "var(--color-surface-input)",
    borderRadius: "0.25rem",
    fontFamily: "var(--font-mono)",
    fontSize: "0.9em",
    paddingBottom: "0.125rem",
    paddingLeft: "0.25rem",
    paddingRight: "0.25rem",
    paddingTop: "0.125rem",
  },
  em: { fontStyle: "italic" },
  headingLarge: {
    fontFamily: "var(--font-sans)",
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    marginBottom: "0.25rem",
    marginTop: "0.75rem",
    overflowWrap: "normal",
    ":first-child": { marginTop: 0 },
  },
  headingSmall: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    marginBottom: "0.25rem",
    marginTop: "0.75rem",
    overflowWrap: "normal",
    ":first-child": { marginTop: 0 },
  },
  headingCompact: {
    marginTop: "0.5rem",
    ":first-child": { marginTop: 0 },
  },
  horizontalRule: {
    borderBottomWidth: 0,
    borderColor: "var(--color-line)",
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderStyle: "solid",
    borderTopWidth: "1px",
    height: 0,
    marginBottom: "0.75rem",
    marginTop: "0.75rem",
  },
  invalidLink: {
    color: "var(--color-ink-muted)",
    textDecorationLine: "underline",
    textDecorationStyle: "dotted",
  },
  item: {
    marginBottom: "0.125rem",
    marginTop: "0.125rem",
    overflowWrap: "normal",
  },
  link: {
    color: "var(--color-accent)",
    textDecorationLine: "underline",
    textUnderlineOffset: "0.125rem",
  },
  list: {
    listStyleImage: "none",
    listStylePosition: "outside",
    marginBottom: "0.5rem",
    marginTop: "0.5rem",
    paddingInlineStart: "1.25rem",
  },
  orderedList: { listStyleType: "decimal" },
  paragraph: {
    lineHeight: 1.625,
    marginBottom: "0.5rem",
    marginTop: "0.5rem",
    overflowWrap: "break-word",
    ":first-child": { marginTop: 0 },
    ":last-child": { marginBottom: 0 },
  },
  pre: {
    backgroundColor: "var(--color-surface)",
    borderColor: "var(--color-line)",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: "0.5rem",
    marginTop: "0.5rem",
    overflowX: "auto",
    padding: "0.5rem",
  },
  root: {
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
  },
  strong: { fontWeight: 600 },
  table: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: "0.75rem",
    lineHeight: "1rem",
  },
  tableCell: {
    borderColor: "var(--color-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    paddingBottom: "0.25rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.25rem",
    verticalAlign: "top",
  },
  tableHeader: {
    borderColor: "var(--color-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    fontWeight: 600,
    paddingBottom: "0.25rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.25rem",
    textAlign: "start",
  },
  tableWrapper: {
    marginBottom: "0.5rem",
    marginTop: "0.5rem",
    overflowX: "auto",
  },
  unavailableImage: {
    color: "var(--color-ink-muted)",
    fontStyle: "italic",
  },
  unorderedList: { listStyleType: "disc" },
});
