export const HOSTED_PUBLIC_FUNCTION_AUTHORITY = Object.freeze({
  "account:current": "verified_identity",
  "accountDeletion:request": "verified_identity",
  "accountDeletion:status": "status_capability",
  "auth:isAuthenticated": "convex_auth",
  "auth:signIn": "convex_auth",
  "auth:signOut": "convex_auth",
  "commands:acknowledgeReceipt": "active_device",
  "commands:cancelPending": "active_device",
  "commands:enqueue": "active_device",
  "commands:get": "active_device",
  "commands:listForSession": "active_device",
  "commands:listNonterminalForTargetPage": "active_device",
  "commands:listPendingForTarget": "active_device",
  "commands:listPendingForTargetPage": "active_device",
  "commands:markEffectStarted": "active_device",
  "commands:prepare": "active_device",
  "commands:recoverEffectStarted": "active_device",
  "commands:settle": "active_device",
  "deviceRevocation:status": "active_device",
  "devices:approve": "active_device",
  "devices:beginBind": "registered_device",
  "devices:currentRegistration": "verified_identity",
  "devices:finishBind": "verified_identity_and_device_signature",
  "devices:get": "registered_device",
  "devices:list": "registered_device",
  "devices:listKeyEnvelopes": "active_device",
  "devices:listPage": "registered_device",
  "devices:recoverRegistration": "verified_identity",
  "devices:register": "verified_identity",
  "devices:revoke": "active_device",
  "leases:acquire": "active_device",
  "leases:current": "active_device",
  "leases:heartbeat": "active_device",
  "presence:connect": "registered_device",
  "presence:current": "registered_device",
  "presence:disconnect": "registered_device",
  "presence:heartbeat": "registered_device",
  "sessions:appendChunk": "active_device",
  "sessions:beginCompactEpoch": "active_device",
  "sessions:create": "active_device",
  "sessions:getChunks": "active_device",
  "sessions:getHead": "active_device",
  "sessions:getLatestChunks": "active_device",
  "sessions:listHeads": "active_device",
  "sessions:listHeadsPage": "active_device",
  "sessions:updateMetadata": "active_device",
  "sessions:updateState": "active_device",
  "usage:getAccountBinding": "active_device",
  "usage:listAccounts": "active_device",
  "usage:listSnapshots": "active_device",
  "usage:upsertAccount": "active_device",
  "usage:upsertSnapshot": "active_device",
} as const);

export type HostedPublicAuthorityPolicy =
  typeof HOSTED_PUBLIC_FUNCTION_AUTHORITY[keyof typeof HOSTED_PUBLIC_FUNCTION_AUTHORITY];
