import { createHash } from "node:crypto";
import {
  chmod,
  cp,
  lstat,
  mkdir,
  mkdtemp,
  readFile,
  realpath,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";

import { Database } from "bun:sqlite";

const released = {
  archiveBytes: 808_632,
  archiveName: "hraness-hra-0.5.0.tgz",
  archiveSha256: "d0d958a95b15989f639e60ba90a2abefa7d01a3c54af601c300657d365f39063",
  archiveSRI: "sha512-lpiJw1nEDc1CKVpnbtvw4+3+3DZAAKDJ2rvP0VZCwfzatP3gEMh6iTQNQjvZn1z4kyKCQcwo//cRg3/HLyz27Q==",
  packageName: "@hraness/hra",
  schemaVersion: 33,
  stateStoreSha256: "9c40a3a616f308c7387ba2861e3307624f75019aed79608626a0a7325e04caad",
  tag: "v0.5.0",
  tagCommit: "846f5c99f573f97ce99f1f23ac1ea45d93e63042",
  version: "0.5.0",
} as const;

const fixtureDirectory = dirname(import.meta.path);
const repositoryRoot = resolve(fixtureDirectory, "../../..");
const outputDirectory = join(fixtureDirectory, "v0.5.0");

const sha256 = (bytes: Uint8Array | string): string =>
  createHash("sha256").update(bytes).digest("hex");

const sha512SRI = (bytes: Uint8Array): string =>
  `sha512-${createHash("sha512").update(bytes).digest("base64")}`;

const run = async (command: string, args: readonly string[], cwd: string): Promise<string> => {
  const child = Bun.spawn([command, ...args], {
    cwd,
    env: process.env,
    stderr: "pipe",
    stdin: "ignore",
    stdout: "pipe",
  });
  const [exitCode, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  if (exitCode !== 0) {
    throw new Error(`${command} failed (${String(exitCode)}): ${stderr.slice(0, 4_096)}`);
  }
  return stdout;
};

const sqlIdentifier = (value: string): string => `"${value.replaceAll('"', '""')}"`;

const sqlLiteral = (value: unknown): string => {
  if (value === null) return "NULL";
  if (typeof value === "number" || typeof value === "bigint") return String(value);
  if (typeof value === "string") return `'${value.replaceAll("'", "''")}'`;
  if (value instanceof Uint8Array) return `X'${Buffer.from(value).toString("hex")}'`;
  throw new Error(`Unsupported SQLite fixture value: ${Object.prototype.toString.call(value)}`);
};

const logicalDump = (databasePath: string): string => {
  const database = new Database(databasePath, { create: false, readonly: true, strict: true });
  try {
    const objects = database.query(
      `SELECT type,name,tbl_name,sql FROM sqlite_schema
       WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
       ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'view' THEN 2 ELSE 3 END,name`,
    ).all() as Array<{ type: string; name: string; tbl_name: string; sql: string }>;
    const tables = objects.filter((object) => object.type === "table");
    const later = objects.filter((object) => object.type !== "table");
    const lines = [
      "-- Logical state root generated by the exact public @hraness/hra v0.5.0 package.",
      "-- See manifest.json and generate-v0.5.0.ts for provenance and reproduction.",
      "PRAGMA foreign_keys=OFF;",
      "BEGIN IMMEDIATE;",
    ];
    for (const table of tables) {
      lines.push(`${table.sql};`);
      const columns = database.query(`PRAGMA table_info(${sqlIdentifier(table.name)})`).all() as Array<{
        name: string;
        pk: number;
      }>;
      const names = columns.map(({ name }) => name);
      const primary = columns.filter(({ pk }) => pk > 0).sort((left, right) => left.pk - right.pk);
      const order = primary.length > 0
        ? primary.map(({ name }) => sqlIdentifier(name)).join(",")
        : "rowid";
      const rows = database.query(
        `SELECT * FROM ${sqlIdentifier(table.name)} ORDER BY ${order}`,
      ).all() as Array<Record<string, unknown>>;
      for (const row of rows) {
        lines.push(
          `INSERT INTO ${sqlIdentifier(table.name)}(${names.map(sqlIdentifier).join(",")}) VALUES(${names.map((name) => sqlLiteral(row[name])).join(",")});`,
        );
      }
    }
    for (const object of later) lines.push(`${object.sql};`);
    lines.push(`PRAGMA user_version=${String(released.schemaVersion)};`, "COMMIT;", "");
    return lines.join("\n");
  } finally {
    database.close(false);
  }
};

const readExpectedRows = (databasePath: string): Record<string, unknown> => {
  const database = new Database(databasePath, { create: false, readonly: true, strict: true });
  try {
    return {
      migrations: database.query(
        "SELECT MIN(version) AS first,MAX(version) AS last,COUNT(*) AS count FROM migrations",
      ).get(),
      profiles: database.query(
        "SELECT id,label,state,process_generation FROM profiles ORDER BY id",
      ).all(),
      projects: database.query(
        "SELECT id,label,root_path,is_default FROM projects ORDER BY id",
      ).all(),
      sessions: database.query(
        "SELECT id,profile_id,project_id,title,provider,preset,state,revision FROM sessions ORDER BY id",
      ).all(),
      queueEntries: database.query(
        "SELECT id,session_id,message,state,enqueue_sequence FROM queue_entries ORDER BY id",
      ).all(),
      queueSequenceAuthority: database.query(
        "SELECT next_sequence FROM queue_sequence_authority WHERE singleton=1",
      ).get(),
    };
  } finally {
    database.close(false);
  }
};

const listDirectories = async (root: string, at = root): Promise<string[]> => {
  const glob = new Bun.Glob("*");
  const results: string[] = [];
  for await (const name of glob.scan({ cwd: at, dot: true, onlyFiles: false })) {
    const path = join(at, name);
    const metadata = await lstat(path);
    if (!metadata.isDirectory() || metadata.isSymbolicLink()) continue;
    results.push(relative(root, path).split(sep).join("/"));
    results.push(...await listDirectories(root, path));
  }
  return results.sort();
};

const main = async (): Promise<void> => {
  const [archiveArgument, update] = process.argv.slice(2);
  if (archiveArgument === undefined || update !== "--update") {
    throw new Error("Usage: bun scripts/fixtures/released-state/generate-v0.5.0.ts <hraness-hra-0.5.0.tgz> --update");
  }
  const archive = await realpath(resolve(archiveArgument));
  const archiveMetadata = await lstat(archive);
  const archiveBytes = await readFile(archive);
  if (
    !archiveMetadata.isFile()
    || archiveMetadata.isSymbolicLink()
    || archiveMetadata.nlink !== 1
    || archiveMetadata.size !== released.archiveBytes
    || sha256(archiveBytes) !== released.archiveSha256
    || sha512SRI(archiveBytes) !== released.archiveSRI
  ) throw new Error("The supplied archive is not the exact public @hraness/hra v0.5.0 artifact.");

  const temporary = await realpath(await mkdtemp(join(tmpdir(), "hra-released-state-fixture-")));
  try {
    const listing = (await run("tar", ["-tzf", archive], temporary)).split("\n").filter(Boolean);
    if (
      listing.length < 1
      || listing.length > 512
      || listing.some((entry) => !entry.startsWith("package/") || entry.includes("..") || entry.startsWith("/"))
    ) throw new Error("The released archive has an unsafe or unexpected path manifest.");
    await run("tar", ["-xzf", archive, "-C", temporary], temporary);
    await symlink(join(repositoryRoot, "node_modules"), join(temporary, "node_modules"), "dir");

    const packageRoot = join(temporary, "package");
    const packageJsonBytes = await readFile(join(packageRoot, "package.json"));
    const packageJson = JSON.parse(packageJsonBytes.toString("utf8")) as Record<string, unknown>;
    if (packageJson.name !== released.packageName || packageJson.version !== released.version) {
      throw new Error("The released archive package identity is invalid.");
    }
    const stateStoreSource = await readFile(join(packageRoot, "src/storage/state-store.ts"));
    if (
      sha256(stateStoreSource) !== released.stateStoreSha256
      || !stateStoreSource.toString("utf8").includes(`const currentSchemaVersion = ${String(released.schemaVersion)};`)
      || !stateStoreSource.toString("utf8").includes("STATE_SCHEMA_NEWER:${version}:${currentSchemaVersion}")
    ) throw new Error("The released StateStore source no longer matches the reviewed schema guard.");

    const pathsModule = await import(pathToFileURL(join(packageRoot, "src/storage/paths.ts")).href) as {
      initializeProfilePaths: (paths: unknown, profileId: string) => Promise<unknown>;
      initializeStatePaths: (paths: unknown) => Promise<void>;
      resolveStatePaths: (input: { rootDirectory: string }) => { database: string; root: string };
    };
    const stateModule = await import(pathToFileURL(join(packageRoot, "src/storage/state-store.ts")).href) as {
      StateStore: new (paths: unknown, options?: { now?: () => number; readonly?: boolean }) => {
        close: () => void;
        createProfile: (label: string) => { id: string };
        createProject: (label: string, root: string, makeDefault: boolean) => Promise<{ id: string }>;
        createSession: (input: {
          fastEnabled: boolean;
          preset: "high";
          profileId: string;
          projectId: string;
          title: string;
        }) => { id: string };
        enqueue: (sessionId: string, message: string) => unknown;
      };
    };

    const stateRoot = join(temporary, "state-root");
    const paths = pathsModule.resolveStatePaths({ rootDirectory: stateRoot });
    await pathsModule.initializeStatePaths(paths);
    let now = 1_700_000_000_000;
    const store = new stateModule.StateStore(paths, { now: () => now++ });
    const profile = store.createProfile("Released fixture account");
    await pathsModule.initializeProfilePaths(paths, profile.id);
    const projectRoot = join(temporary, "project-root");
    await mkdir(projectRoot, { mode: 0o700 });
    const project = await store.createProject("Released fixture project", projectRoot, true);
    const session = store.createSession({
      fastEnabled: false,
      preset: "high",
      profileId: profile.id,
      projectId: project.id,
      title: "Released fixture session",
    });
    store.enqueue(session.id, "Preserve this released queue entry");
    store.close();

    const portableProjectRoot = "/fixture/hra-v0.5.0/project";
    const fixtureDatabase = new Database(paths.database, { create: false, strict: true });
    fixtureDatabase.query("UPDATE projects SET root_path=? WHERE id=?").run(portableProjectRoot, project.id);
    const checkpoint = fixtureDatabase.query("PRAGMA wal_checkpoint(TRUNCATE)").get();
    fixtureDatabase.close(false);
    await chmod(paths.database, 0o600);
    if (await Bun.file(`${paths.database}-wal`).exists()) {
      const wal = await lstat(`${paths.database}-wal`);
      if (wal.size !== 0) throw new Error("Released fixture WAL did not truncate.");
    }

    const releasedReader = new stateModule.StateStore(paths, { readonly: true });
    releasedReader.close();

    const newerRoot = join(temporary, "newer-root");
    await cp(stateRoot, newerRoot, { recursive: true });
    const newerPaths = pathsModule.resolveStatePaths({ rootDirectory: newerRoot });
    const newerDatabase = new Database(newerPaths.database, { create: false, strict: true });
    newerDatabase.exec("PRAGMA user_version=35");
    newerDatabase.query("PRAGMA wal_checkpoint(TRUNCATE)").get();
    newerDatabase.close(false);
    let releasedReadonlyNewerError: string | undefined;
    try {
      const impossible = new stateModule.StateStore(newerPaths, { readonly: true });
      impossible.close();
    } catch (error) {
      releasedReadonlyNewerError = error instanceof Error ? error.message : String(error);
    }
    if (releasedReadonlyNewerError !== "STATE_SCHEMA_NEWER:35:33") {
      throw new Error(`Released downgrade guard was not proved: ${String(releasedReadonlyNewerError)}`);
    }

    const stateSql = logicalDump(paths.database);
    const stateSqlBytes = Buffer.from(stateSql, "utf8");
    const rootDirectories = await listDirectories(stateRoot);
    const expectedRows = readExpectedRows(paths.database);
    const manifest = {
      schemaVersion: 1,
      source: {
        archiveBytes: released.archiveBytes,
        archiveName: released.archiveName,
        archiveSha256: released.archiveSha256,
        archiveSRI: released.archiveSRI,
        packageName: released.packageName,
        stateStoreSha256: released.stateStoreSha256,
        tag: released.tag,
        tagCommit: released.tagCommit,
        version: released.version,
      },
      state: {
        databaseRelativePath: "control-plane.sqlite",
        expectedRows,
        releasedSchemaVersion: released.schemaVersion,
        rootDirectories,
        sqlBytes: stateSqlBytes.byteLength,
        sqlSha256: sha256(stateSqlBytes),
        walCheckpoint: checkpoint,
      },
      downgradeProof: {
        probedNewerSchemaVersion: 35,
        releasedReadonlyError: releasedReadonlyNewerError,
      },
    };

    await mkdir(outputDirectory, { recursive: true, mode: 0o700 });
    await writeFile(join(outputDirectory, "control-plane.sql"), stateSqlBytes, { mode: 0o600 });
    await writeFile(
      join(outputDirectory, "manifest.json"),
      `${JSON.stringify(manifest, null, 2)}\n`,
      { mode: 0o600 },
    );
    process.stdout.write(`Wrote ${relative(repositoryRoot, outputDirectory)} from ${released.archiveName}.\n`);
  } finally {
    await rm(temporary, { force: true, recursive: true });
  }
};

await main();
