import * as stylex from "@stylexjs/stylex";

const hoverCapable = "@media (hover: hover)";
const reducedMotion = "@media (prefers-reduced-motion: reduce)";

export const badgeStyles = stylex.create({
  root: {
    alignItems: "center",
    borderBottomLeftRadius: "9999px",
    borderBottomRightRadius: "9999px",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopLeftRadius: "9999px",
    borderTopRightRadius: "9999px",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "inline-flex",
    fontSize: "0.75rem",
    fontWeight: 500,
    lineHeight: "1rem",
    paddingBottom: "0.125rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.125rem",
  },
  accent: {
    borderBottomColor: "var(--color-info)",
    borderLeftColor: "var(--color-info)",
    borderRightColor: "var(--color-info)",
    borderTopColor: "var(--color-info)",
    color: "var(--color-info)",
  },
  attention: {
    borderBottomColor: "var(--color-attention)",
    borderLeftColor: "var(--color-attention)",
    borderRightColor: "var(--color-attention)",
    borderTopColor: "var(--color-attention)",
    color: "var(--color-attention)",
  },
  danger: {
    borderBottomColor: "var(--color-danger)",
    borderLeftColor: "var(--color-danger)",
    borderRightColor: "var(--color-danger)",
    borderTopColor: "var(--color-danger)",
    color: "var(--color-danger)",
  },
  neutral: {
    borderBottomColor: "var(--color-line)",
    borderLeftColor: "var(--color-line)",
    borderRightColor: "var(--color-line)",
    borderTopColor: "var(--color-line)",
    color: "var(--color-ink-muted)",
  },
});

export const buttonStyles = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "currentColor",
    borderBottomLeftRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomStyle: "solid",
    borderBottomWidth: 0,
    borderLeftColor: "currentColor",
    borderLeftStyle: "solid",
    borderLeftWidth: 0,
    borderRightColor: "currentColor",
    borderRightStyle: "solid",
    borderRightWidth: 0,
    borderTopColor: "currentColor",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderTopStyle: "solid",
    borderTopWidth: 0,
    display: "inline-flex",
    fontWeight: 500,
    gap: "0.5rem",
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    transitionDelay: "0s",
    transitionDuration: { default: "150ms", [reducedMotion]: "0s" },
    transitionProperty: "opacity",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    cursor: { default: null, ":disabled": "not-allowed" },
    opacity: { default: null, ":disabled": 0.5 },
  },
  defaultSize: {
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    minHeight: "2.75rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
  },
  iconSize: {
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    minHeight: "2.75rem",
    minWidth: "2.75rem",
  },
  smallSize: {
    fontSize: "0.75rem",
    lineHeight: "1rem",
    minHeight: "2.75rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
  },
  primary: {
    ":hover:not(:disabled)": {
      opacity: { default: null, [hoverCapable]: 0.9 },
    },
    backgroundColor: "var(--color-accent)",
    color: "var(--color-accent-ink)",
  },
  secondary: {
    ":hover": {
      borderBottomColor: { default: null, [hoverCapable]: "var(--color-ink-muted)" },
      borderLeftColor: { default: null, [hoverCapable]: "var(--color-ink-muted)" },
      borderRightColor: { default: null, [hoverCapable]: "var(--color-ink-muted)" },
      borderTopColor: { default: null, [hoverCapable]: "var(--color-ink-muted)" },
    },
    backgroundColor: "var(--color-surface-raised)",
    borderBottomColor: "var(--color-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-line)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-line)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink)",
  },
  ghost: {
    ":hover": {
      backgroundColor: { default: null, [hoverCapable]: "var(--color-surface-raised)" },
      color: { default: null, [hoverCapable]: "var(--color-ink)" },
    },
    backgroundColor: "transparent",
    color: "var(--color-ink-muted)",
  },
  danger: {
    ":hover:not(:disabled)": {
      opacity: { default: null, [hoverCapable]: 0.9 },
    },
    backgroundColor: "var(--color-danger)",
    color: "var(--color-danger-ink)",
  },
});

export const cardStyles = stylex.create({
  root: {
    backgroundColor: "var(--color-surface-raised)",
    borderBottomColor: "var(--color-line)",
    borderBottomLeftRadius: "0.5rem",
    borderBottomRightRadius: "0.5rem",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-line)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-line)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-line)",
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: "0.5rem",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink)",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    paddingBottom: "0.75rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: "0.75rem",
  },
  title: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: 1.375,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  description: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  content: {
    paddingBottom: "0.75rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
  },
  footer: {
    alignItems: "center",
    display: "flex",
    gap: "0.5rem",
    paddingBottom: "0.75rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
  },
});

export const dialogStyles = stylex.create({
  root: {
    "::backdrop": {
      backgroundColor: "var(--scrim)",
    },
    backgroundColor: "var(--color-surface-raised)",
    borderBottomColor: "var(--color-line)",
    borderBottomLeftRadius: "0.5rem",
    borderBottomRightRadius: "0.5rem",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-line)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-line)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-line)",
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: "0.5rem",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink)",
    marginBottom: "auto",
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: "auto",
    paddingBottom: "1rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    paddingTop: "1rem",
    width: "min(32rem, calc(100vw - 2rem))",
  },
  title: {
    fontFamily: "var(--font-sans)",
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  description: {
    color: "var(--color-ink-muted)",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.25rem",
    overflowWrap: "normal",
  },
  footer: {
    display: "flex",
    gap: "0.5rem",
    justifyContent: "flex-end",
    marginTop: "1rem",
  },
});

export const dropdownMenuStyles = stylex.create({
  root: {
    position: "relative",
  },
  trigger: {
    ":hover": {
      color: { default: null, [hoverCapable]: "var(--color-ink)" },
    },
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "currentColor",
    borderBottomLeftRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomStyle: "solid",
    borderBottomWidth: 0,
    borderLeftColor: "currentColor",
    borderLeftStyle: "solid",
    borderLeftWidth: 0,
    borderRightColor: "currentColor",
    borderRightStyle: "solid",
    borderRightWidth: 0,
    borderTopColor: "currentColor",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderTopStyle: "solid",
    borderTopWidth: 0,
    color: "var(--color-ink-muted)",
    display: "inline-flex",
    justifyContent: "center",
    minHeight: "2.75rem",
    minWidth: "2.75rem",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  list: {
    backgroundColor: "var(--color-surface-raised)",
    borderBottomColor: "var(--color-line)",
    borderBottomLeftRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-line)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-line)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-line)",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    marginTop: "0.25rem",
    minWidth: "11rem",
    paddingBottom: "0.25rem",
    paddingLeft: "0.25rem",
    paddingRight: "0.25rem",
    paddingTop: "0.25rem",
    position: "absolute",
    zIndex: 10,
  },
  listStart: { insetInlineStart: 0 },
  listEnd: { insetInlineEnd: 0 },
  item: {
    ":hover": {
      backgroundColor: { default: null, [hoverCapable]: "var(--color-surface-input)" },
    },
    cursor: { default: null, ":disabled": "not-allowed" },
    opacity: { default: null, ":disabled": 0.5 },
    backgroundColor: "transparent",
    borderBottomColor: "currentColor",
    borderBottomLeftRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem",
    borderBottomStyle: "solid",
    borderBottomWidth: 0,
    borderLeftColor: "currentColor",
    borderLeftStyle: "solid",
    borderLeftWidth: 0,
    borderRightColor: "currentColor",
    borderRightStyle: "solid",
    borderRightWidth: 0,
    borderTopColor: "currentColor",
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem",
    borderTopStyle: "solid",
    borderTopWidth: 0,
    display: "block",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    minHeight: "2.75rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingBottom: 0,
    paddingTop: 0,
    textAlign: "start",
    width: "100%",
  },
  itemDefault: { color: "var(--color-ink)" },
  itemDanger: { color: "var(--color-danger)" },
});

export const fieldStyles = stylex.create({
  input: {
    "::placeholder": { color: "var(--color-ink-muted)", opacity: 1 },
    backgroundColor: "var(--color-surface-input)",
    borderBottomColor: "var(--color-control)",
    borderBottomLeftRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-control)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-control)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-control)",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink)",
    cursor: { default: null, ":disabled": "not-allowed" },
    fontSize: "1rem",
    lineHeight: "1.5rem",
    minHeight: "2.75rem",
    opacity: { default: null, ":disabled": 0.5 },
    paddingBottom: 0,
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: 0,
    width: "100%",
  },
  textarea: {
    "::placeholder": { color: "var(--color-ink-muted)", opacity: 1 },
    backgroundColor: "var(--color-surface-input)",
    borderBottomColor: "var(--color-control)",
    borderBottomLeftRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-control)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-control)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-control)",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink)",
    cursor: { default: null, ":disabled": "not-allowed" },
    fontSize: "1rem",
    lineHeight: "1.5rem",
    minHeight: "2.75rem",
    opacity: { default: null, ":disabled": 0.5 },
    paddingBottom: "0.5rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: "0.5rem",
    resize: "none",
    width: "100%",
  },
});

export const sheetStyles = stylex.create({
  root: {
    "::backdrop": {
      backgroundColor: "var(--scrim)",
    },
    backgroundColor: "var(--color-surface-raised)",
    borderBottomColor: "var(--color-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-line)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-line)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink)",
    maxHeight: "85dvh",
    overflowY: "auto",
    paddingBottom: "1rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    paddingTop: "1rem",
  },
  bottom: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: "0.5rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "auto",
    maxWidth: "none",
    paddingBottom: "calc(1rem + env(safe-area-inset-bottom))",
    width: "100%",
  },
  right: {
    borderBottomLeftRadius: "0.5rem",
    borderBottomRightRadius: 0,
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: 0,
    height: "100%",
    marginBottom: 0,
    marginLeft: "auto",
    marginRight: 0,
    marginTop: 0,
    maxHeight: "none",
    maxWidth: "none",
    paddingRight: "calc(1rem + env(safe-area-inset-right))",
    width: "min(28rem, 100vw)",
  },
});

export const switchStyles = stylex.create({
  root: {
    cursor: { default: null, ":disabled": "not-allowed" },
    opacity: { default: null, ":disabled": 0.5 },
    alignItems: "center",
    borderBottomColor: "var(--color-line)",
    borderBottomLeftRadius: "9999px",
    borderBottomRightRadius: "9999px",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderLeftColor: "var(--color-line)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderRightColor: "var(--color-line)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: "var(--color-line)",
    borderTopLeftRadius: "9999px",
    borderTopRightRadius: "9999px",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "inline-flex",
    flexShrink: 0,
    height: "1.5rem",
    position: "relative",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    transitionDelay: "0s",
    transitionDuration: { default: "150ms", [reducedMotion]: "0s" },
    transitionProperty:
      "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    width: "2.75rem",
  },
  checked: { backgroundColor: "var(--color-accent)" },
  unchecked: { backgroundColor: "var(--color-surface-input)" },
  knob: {
    backgroundColor: "var(--color-ink)",
    borderBottomLeftRadius: "9999px",
    borderBottomRightRadius: "9999px",
    borderTopLeftRadius: "9999px",
    borderTopRightRadius: "9999px",
    display: "block",
    height: "1rem",
    pointerEvents: "none",
    position: "relative",
    transitionDelay: "0s",
    transitionDuration: { default: "150ms", [reducedMotion]: "0s" },
    transitionProperty: "inset-inline-start",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    width: "1rem",
  },
  knobChecked: { backgroundColor: "var(--color-accent-ink)", insetInlineStart: "1.5rem" },
  knobUnchecked: { insetInlineStart: "0.25rem" },
});
