import * as stylex from "@stylexjs/stylex";

export const attachmentChipStyles = stylex.create({
  chip: {
    alignItems: "center",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    gap: "0.5rem",
    maxWidth: "100%",
    overflowWrap: "normal",
    paddingBottom: "0.25rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.25rem",
  },
  dangerBorder: { borderColor: "var(--color-danger)" },
  detail: {
    color: "var(--color-ink-muted)",
    fontSize: "0.7rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  error: {
    color: "var(--color-danger)",
    fontSize: "0.7rem",
  },
  itemStack: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  lineBorder: { borderColor: "var(--color-line)" },
  list: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
    listStyleImage: "none",
    listStylePosition: "outside",
    listStyleType: "none",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    padding: 0,
  },
  messageList: { justifyContent: "flex-end" },
  name: {
    color: "var(--color-ink)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  thumbnail: {
    height: "2.5rem",
    borderColor: "var(--color-line)",
    borderRadius: "0.25rem",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "block",
    flexShrink: 0,
    width: "2.5rem",
    objectFit: "cover",
  },
});
