import * as stylex from "@stylexjs/stylex";

export const interactionPanelStyles = stylex.create({
  actionRow: {
    display: "flex",
    gap: "0.5rem",
  },
  answerStack: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginTop: "0.75rem",
  },
  badges: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  detail: {
    color: "var(--color-ink-muted)",
    marginTop: "0.5rem",
  },
  fieldset: {
    borderWidth: 0,
    display: "flex",
    flexDirection: "column",
    fontSize: "0.75rem",
    gap: "0.25rem",
    lineHeight: "1rem",
    margin: 0,
    padding: 0,
  },
  headline: {
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.5rem",
    overflowWrap: "break-word",
  },
  header: {
    alignItems: "center",
    display: "flex",
    gap: "0.5rem",
    justifyContent: "space-between",
  },
  legend: {
    color: "var(--color-ink)",
    fontWeight: 500,
    overflowWrap: "break-word",
    padding: 0,
  },
  option: {
    alignItems: "flex-start",
    borderColor: "var(--color-line)",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    gap: "0.5rem",
    minHeight: "2.75rem",
    padding: "0.5rem",
  },
  optionDescription: { color: "var(--color-ink-muted)" },
  optionText: {
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
    overflowWrap: "break-word",
  },
  question: {
    color: "var(--color-ink-muted)",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "break-word",
  },
  quiet: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  radio: {
    color: "inherit",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.25rem",
    padding: 0,
  },
  reason: {
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  reasons: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginTop: "0.75rem",
  },
  root: {
    backgroundColor: "var(--color-surface-raised)",
    borderColor: "var(--color-attention)",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "0.75rem",
  },
  spacedActionRow: { marginTop: "0.75rem" },
  status: { marginTop: "0.5rem" },
});
