import * as stylex from "@stylexjs/stylex";

const reducedMotion = "@media (prefers-reduced-motion: reduce)";
const hoverCapable = "@media (hover: hover)";

const attentionPulse = stylex.keyframes({
  "0%": { boxShadow: "0 0 0 1px var(--color-attention)" },
  "50%": {
    boxShadow: "0 0 0 3px color-mix(in oklab, var(--color-attention) 45%, transparent)",
  },
  "100%": { boxShadow: "0 0 0 1px var(--color-attention)" },
});

export const sessionCardStyles = stylex.create({
  attention: {
    animationComposition: { default: "replace", [reducedMotion]: "replace" },
    animationDelay: { default: "0s", [reducedMotion]: "0s" },
    animationDirection: { default: "normal", [reducedMotion]: "normal" },
    animationDuration: {
      default: "2.4s",
      [reducedMotion]: "0s",
    },
    animationFillMode: { default: "none", [reducedMotion]: "none" },
    animationIterationCount: {
      default: "infinite",
      [reducedMotion]: 1,
    },
    animationName: {
      default: attentionPulse,
      [reducedMotion]: "none",
    },
    animationPlayState: { default: "running", [reducedMotion]: "running" },
    animationRangeEnd: { default: "normal", [reducedMotion]: "normal" },
    animationRangeStart: { default: "normal", [reducedMotion]: "normal" },
    animationTimeline: { default: "auto", [reducedMotion]: "auto" },
    animationTimingFunction: {
      default: "ease-in-out",
      [reducedMotion]: "ease",
    },
    borderBottomColor: "var(--color-attention)",
    borderLeftColor: "var(--color-attention)",
    borderRightColor: "var(--color-attention)",
    borderTopColor: "var(--color-attention)",
  },
  card: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
  },
  dialogInput: { marginTop: "0.75rem" },
  dialogValue: {
    fontFamily: "var(--font-mono)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.75rem",
    overflowWrap: "normal",
    userSelect: "all",
    wordBreak: "break-all",
  },
  dragHandle: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: 0,
    color: "var(--color-ink-muted)",
    cursor: "grab",
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    minHeight: "2.75rem",
    minWidth: "2.75rem",
    padding: 0,
    touchAction: "none",
    ":hover": {
      color: { default: null, [hoverCapable]: "var(--color-ink)" },
    },
  },
  dragging: { opacity: 0.6 },
  header: {
    alignItems: "flex-start",
    display: "flex",
    gap: "0.25rem",
    paddingBottom: "0.5rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: "0.75rem",
  },
  lastPrompt: {
    color: "var(--color-ink-muted)",
    display: "-webkit-box",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  menu: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: "0.25rem",
  },
  notice: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
    paddingBottom: "0.5rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
  },
  openButton: {
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: 0,
    color: "inherit",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: "0.375rem",
    minWidth: 0,
    padding: 0,
    textAlign: "left",
  },
  quiet: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
  },
  selected: {
    borderBottomColor: "var(--color-accent)",
    borderLeftColor: "var(--color-accent)",
    borderRightColor: "var(--color-accent)",
    borderTopColor: "var(--color-accent)",
  },
  title: {
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
