import * as stylex from "@stylexjs/stylex";

const hoverCapable = "@media (hover: hover)";

export const settingsListStyles = stylex.create({
  card: {
    display: "flex",
    flexDirection: "column",
  },
  choice: {
    alignItems: "center",
    borderColor: "currentColor",
    borderRadius: "0.25rem",
    borderStyle: "solid",
    borderWidth: 0,
    display: "inline-flex",
    fontSize: "0.75rem",
    fontWeight: 500,
    justifyContent: "center",
    lineHeight: "1rem",
    minHeight: "2.75rem",
    paddingBottom: 0,
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: 0,
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.5,
    },
  },
  choiceGroup: {
    alignItems: "center",
    borderColor: "var(--color-line)",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.25rem",
    padding: "0.25rem",
  },
  choiceIdle: {
    backgroundColor: "transparent",
    color: "var(--color-ink-muted)",
    ":hover": {
      color: { default: null, [hoverCapable]: "var(--color-ink)" },
    },
  },
  choiceSelected: {
    backgroundColor: "var(--color-accent)",
    color: "var(--color-surface)",
  },
  code: {
    backgroundColor: "var(--color-surface-input)",
    borderRadius: "0.25rem",
    color: "var(--color-ink-muted)",
    display: "block",
    fontFamily: "var(--font-mono)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    overflowX: "auto",
    paddingBottom: "0.25rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.25rem",
  },
  control: {
    alignItems: "center",
    display: "flex",
    gap: "0.5rem",
  },
  description: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  empty: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
    padding: "0.75rem",
    ":not(:last-child)": {
      borderBottomColor: "var(--color-line)",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
    },
  },
  icon: {
    display: "block",
    height: "1.25rem",
    verticalAlign: "middle",
    width: "1.25rem",
  },
  row: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    padding: "0.75rem",
    ":not(:last-child)": {
      borderBottomColor: "var(--color-line)",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
    },
  },
  rowBody: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "space-between",
  },
  rowLabel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    minWidth: 0,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },
  title: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  rowTitle: {
    fontSize: "0.875rem",
    fontWeight: 500,
    lineHeight: "1.25rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
