import * as stylex from "@stylexjs/stylex";

export const transcriptStyles = stylex.create({
  thinking: {
    borderColor: "var(--color-line)",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
  },
  thinkingButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: 0,
    color: "var(--color-ink-muted)",
    display: "flex",
    fontSize: "0.75rem",
    gap: "0.25rem",
    width: "100%",
    lineHeight: "1rem",
    minHeight: "2.75rem",
    paddingBottom: 0,
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: 0,
    textAlign: "start",
  },
  thinkingText: {
    borderTopColor: "var(--color-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "break-word",
    paddingBottom: "0.5rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: "0.5rem",
    whiteSpace: "pre-wrap",
  },
  transcript: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  turnMarker: {
    borderTopColor: "var(--color-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
    paddingTop: "0.5rem",
  },
  userActor: {
    color: "var(--color-ink-muted)",
    fontSize: "0.7rem",
    letterSpacing: "0.025em",
    textTransform: "uppercase",
  },
  userBubble: {
    alignItems: "flex-end",
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },
  userText: {
    backgroundColor: "var(--color-surface-input)",
    borderColor: "var(--color-line)",
    borderRadius: "0.5rem",
    borderStartEndRadius: "0.125rem",
    borderStyle: "solid",
    borderWidth: "1px",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    maxWidth: "85%",
    overflowWrap: "break-word",
    paddingBottom: "0.5rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: "0.5rem",
    whiteSpace: "pre-wrap",
  },
});
