import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import fc from "fast-check";

import { INTERACTION_MAX_PENDING_MS } from "../domain/interactions.ts";

import { CodexError } from "./errors.ts";
import { resolvePinnedCodexRuntime } from "./runtime.ts";
import {
  PINNED_CODEX_NOTIFICATION_MATRIX,
  PINNED_CODEX_NOTIFICATION_SCHEMA_DIGEST,
  PINNED_CODEX_SERVER_REQUEST_MATRIX,
  PINNED_CODEX_SERVER_REQUEST_SCHEMA_DIGEST,
  assertPinnedCodexNotificationMatrix,
  assertPinnedCodexServerRequestMatrix,
  codexNotificationDisposition,
  codexServerRequestDisposition,
  compileCodexInteractionResponse,
  parseAccountUsage,
  parseBrokeredCodexServerRequest,
  parseFact,
  parseModelPage,
  parseManagedLoginCancel,
  parsePluginCatalog,
  parseProviderRequestId,
  parseThreadItemsPage,
  parseThreadMetadataRead,
  parseThreadTurnsPage,
  resolvePreset,
  safeLiveAcceptanceCommandDigest,
  type BrokeredCodexServerRequestMethod,
  type CodexCapabilitySnapshot,
} from "./protocol.ts";

const permissionPrivatePath = ["", "Users", "alice", "private", "PERMISSION_VALUE_SENTINEL"].join("/");

const brokeredFixtures: Readonly<Record<BrokeredCodexServerRequestMethod, unknown>> = {
  "item/commandExecution/requestApproval": {
    threadId: "thread-1", turnId: "turn-1", itemId: "item-1", startedAtMs: 1,
    approvalId: null, environmentId: null, reason: "network", command: "git push origin main",
    commandActions: [{ type: "unknown", command: "git push origin main" }],
    networkApprovalContext: { host: "github.com", protocol: "https" },
    additionalPermissions: { network: { enabled: true } },
    cwd: "/workspace", availableDecisions: ["accept", "acceptForSession", "decline", "cancel"],
  },
  "item/fileChange/requestApproval": {
    threadId: "thread-1", turnId: "turn-1", itemId: "item-2", startedAtMs: 1,
    reason: "write files", grantRoot: "/workspace",
  },
  "item/permissions/requestApproval": {
    threadId: "thread-1", turnId: "turn-1", itemId: "item-3", environmentId: null,
    startedAtMs: 1, cwd: "/workspace", reason: "network",
    permissions: {
      network: { enabled: true },
      fileSystem: { read: [permissionPrivatePath] },
    },
  },
  "item/tool/requestUserInput": {
    threadId: "thread-1", turnId: "turn-1", itemId: "item-4", isBlocking: true,
    autoResolutionMs: null,
    questions: [{
      id: "choice", header: "Choice", question: "Which option?", isOther: true, isSecret: false,
      options: [{ label: "A", description: "First" }],
    }],
  },
  "mcpServer/elicitation/request": {
    threadId: "thread-1", turnId: "turn-1", serverName: "example", mode: "form",
    _meta: null, message: "Configure Example",
    requestedSchema: {
      type: "object",
      properties: {
        confirmed: { type: "boolean", title: "Confirm", default: true },
      },
      required: ["confirmed"],
    },
  },
};

const capabilities: CodexCapabilitySnapshot = {
  models: [
    {
      id: "gpt-5.6-luna",
      model: "gpt-5.6-luna",
      displayName: "GPT-5.6 Luna",
      hidden: false,
      supportedReasoningEfforts: ["low", "medium", "high", "max"],
      defaultReasoningEffort: "medium",
      serviceTiers: [{ id: "priority", name: "Fast", description: "Faster" }],
      defaultServiceTier: null,
      isDefault: false,
    },
    {
      id: "gpt-5.6-sol",
      model: "gpt-5.6-sol",
      displayName: "GPT-5.6 Sol",
      hidden: false,
      supportedReasoningEfforts: ["low", "max", "ultra"],
      defaultReasoningEffort: "low",
      serviceTiers: [{ id: "priority", name: "Fast", description: "Faster" }],
      defaultServiceTier: null,
      isDefault: true,
    },
  ],
  features: [],
  permissionProfiles: null,
  apps: null,
  pluginLifecycle: "unsupported-under-development",
};

describe("pinned server requests and safe notifications", () => {
  test("matches schemas generated by the installed pinned experimental runtime", async () => {
    const runtime = await resolvePinnedCodexRuntime();
    const outputDirectory = await mkdtemp(join(tmpdir(), "hra-codex-schema-"));
    try {
      const [bunExecutable, launcher] = runtime.launcherArgv;
      const generated = Bun.spawnSync({
        cmd: [
          bunExecutable,
          launcher,
          "app-server",
          "generate-ts",
          "--experimental",
          "--out",
          outputDirectory,
        ],
        stdout: "pipe",
        stderr: "pipe",
      });
      expect(generated.exitCode).toBe(0);

      const notificationSource = await readFile(
        join(outputDirectory, "ServerNotification.ts"),
        "utf8",
      );
      const requestSource = await readFile(join(outputDirectory, "ServerRequest.ts"), "utf8");
      const methods = (source: string): readonly string[] =>
        [...source.matchAll(/\{ "method": "([^"]+)"/gu)].map((match) => match[1]!);
      const digest = (source: string): string =>
        createHash("sha256").update(source).digest("hex");

      expect(methods(notificationSource)).toEqual(Object.keys(PINNED_CODEX_NOTIFICATION_MATRIX));
      expect(digest(notificationSource)).toBe(PINNED_CODEX_NOTIFICATION_SCHEMA_DIGEST);
      expect(methods(requestSource)).toEqual(Object.keys(PINNED_CODEX_SERVER_REQUEST_MATRIX));
      expect(digest(requestSource)).toBe(PINNED_CODEX_SERVER_REQUEST_SCHEMA_DIGEST);
    } finally {
      await rm(outputDirectory, { recursive: true, force: true });
    }
  });

  test("parses only the pinned closed login-cancellation outcomes", () => {
    expect(parseManagedLoginCancel({ status: "canceled" })).toEqual({ status: "canceled" });
    expect(parseManagedLoginCancel({ status: "notFound" })).toEqual({ status: "notFound" });
    expect(() => parseManagedLoginCancel({ status: "completed" })).toThrow(CodexError);
  });

  test("covers the exact generated 0.149.0 ServerNotification union", () => {
    expect(Object.keys(PINNED_CODEX_NOTIFICATION_MATRIX)).toEqual([
      "error",
      "thread/started",
      "thread/status/changed",
      "thread/archived",
      "thread/deleted",
      "thread/unarchived",
      "thread/closed",
      "thread/reverted",
      "skills/changed",
      "thread/name/updated",
      "thread/goal/updated",
      "thread/goal/cleared",
      "thread/queue/changed",
      "project/changed",
      "thread/project/updated",
      "thread/environment/connected",
      "thread/environment/disconnected",
      "thread/settings/updated",
      "thread/tokenUsage/updated",
      "turn/started",
      "hook/started",
      "turn/completed",
      "hook/completed",
      "turn/diff/updated",
      "turn/plan/updated",
      "item/started",
      "item/autoApprovalReview/started",
      "item/autoApprovalReview/completed",
      "autoApprovalReview/strictReviewRequired",
      "item/completed",
      "rawResponseItem/completed",
      "rawResponse/completed",
      "item/agentMessage/delta",
      "item/plan/delta",
      "command/exec/outputDelta",
      "process/outputDelta",
      "process/exited",
      "item/commandExecution/outputDelta",
      "item/commandExecution/terminalInteraction",
      "item/fileChange/outputDelta",
      "item/fileChange/patchUpdated",
      "serverRequest/resolved",
      "item/mcpToolCall/progress",
      "mcpServer/oauthLogin/completed",
      "mcpServer/startupStatus/updated",
      "account/updated",
      "account/rateLimits/updated",
      "app/list/updated",
      "remoteControl/status/changed",
      "externalAgentConfig/import/progress",
      "externalAgentConfig/import/completed",
      "fs/changed",
      "item/reasoning/summaryTextDelta",
      "item/reasoning/summaryPartAdded",
      "item/reasoning/textDelta",
      "thread/compacted",
      "model/rerouted",
      "model/verification",
      "turn/moderationMetadata",
      "model/safetyBuffering/updated",
      "warning",
      "guardianWarning",
      "deprecationNotice",
      "configWarning",
      "fuzzyFileSearch/sessionUpdated",
      "fuzzyFileSearch/sessionCompleted",
      "thread/realtime/started",
      "thread/realtime/itemAdded",
      "thread/realtime/transcript/delta",
      "thread/realtime/transcript/done",
      "thread/realtime/outputAudio/delta",
      "thread/realtime/sdp",
      "thread/realtime/error",
      "thread/realtime/closed",
      "windows/worldWritableWarning",
      "windowsSandbox/setupCompleted",
      "account/login/completed",
    ]);
    expect(PINNED_CODEX_NOTIFICATION_SCHEMA_DIGEST).toBe(
      "e00fcc3b3c376e808a5feefaa233fdd49ea50acfa15cb629eb40fcf27b706777",
    );
    expect(() => assertPinnedCodexNotificationMatrix()).not.toThrow();
    expect(codexNotificationDisposition("thread/deleted")).toBe("routed");
    expect(codexNotificationDisposition("turn/diff/updated")).toBe("reduced");
    expect(codexNotificationDisposition("thread/realtime/outputAudio/delta")).toBe("ignored");
    expect(codexNotificationDisposition("future/notification")).toBeNull();
  });

  test("routes thread closure and deletion while explicitly discarding reviewed notifications", () => {
    expect(parseFact("thread/closed", { threadId: "thread-1" })).toEqual({
      type: "threadStatusChanged",
      threadId: "thread-1",
      status: { type: "notLoaded" },
    });
    expect(parseFact("thread/deleted", { threadId: "thread-1" })).toEqual({
      type: "threadDeleted",
      threadId: "thread-1",
    });
    expect(parseFact("skills/changed", { private: "discarded" })).toEqual({
      type: "notificationIgnored",
      method: "skills/changed",
    });
    expect(parseFact("future/notification", { private: "discarded" })).toEqual({
      type: "protocolNotice",
      method: "future/notification",
    });
  });

  test("projects plugin discovery without local marketplace paths or load diagnostics", () => {
    const catalog = parsePluginCatalog({
      marketplaces: [{
        name: "official",
        path: "/workspace/.codex/plugins/marketplace.json",
        interface: { displayName: "Official" },
        plugins: [{
          id: "files@official",
          remotePluginId: null,
          version: "1.2.3",
          localVersion: null,
          name: "files",
          shareContext: null,
          source: { type: "local", path: "/private/plugin" },
          installed: false,
          installedAt: null,
          enabled: false,
          installPolicy: "AVAILABLE",
          installPolicySource: null,
          mustShowInstallationInterstitial: null,
          authPolicy: "ON_USE",
          availability: "AVAILABLE",
          disabledReason: null,
          eligiblePlanTypes: ["plus"],
          interface: {
            displayName: "Files",
            shortDescription: "Search files",
            longDescription: null,
            developerName: "OpenAI",
            category: "productivity",
            capabilities: ["search"],
            websiteUrl: null,
            privacyPolicyUrl: null,
            termsOfServiceUrl: null,
            defaultPrompt: null,
            brandColor: null,
            composerIcon: "/private/icon.png",
            composerIconUrl: null,
            logo: null,
            logoDark: null,
            logoUrl: null,
            logoUrlDark: null,
            screenshots: [],
            screenshotUrls: [],
          },
          keywords: ["files"],
        }],
      }],
      marketplaceLoadErrors: [{
        marketplacePath: "/workspace/private/marketplace.json",
        message: "failed at /workspace/private/marketplace.json",
      }],
      featuredPluginIds: ["files@official"],
    });
    expect(catalog).toMatchObject({
      marketplaces: [{
        name: "official",
        plugins: [{
          id: "files@official",
          displayName: "Files",
          sourceType: "local",
          installed: false,
          enabled: false,
        }],
      }],
      marketplaceLoadErrorCount: 1,
      lifecycle: { install: "blocked_compound_upstream_effect" },
    });
    expect(catalog.marketplaces[0]).not.toHaveProperty("path");
    expect(catalog.marketplaces[0]?.plugins[0]).not.toHaveProperty("source");
    expect(catalog).not.toHaveProperty("marketplaceLoadErrors");
    expect(JSON.stringify(catalog)).not.toContain("/workspace/private");
    expect(JSON.stringify(catalog)).not.toContain("/private/plugin");
    expect(JSON.stringify(catalog)).not.toContain("failed at");
  });

  test("covers the exact generated 0.149.0 ServerRequest union with a reviewed schema digest", () => {
    expect(Object.entries(PINNED_CODEX_SERVER_REQUEST_MATRIX)).toEqual([
      ["item/commandExecution/requestApproval", "brokered_interaction"],
      ["item/fileChange/requestApproval", "brokered_interaction"],
      ["item/tool/requestUserInput", "brokered_interaction"],
      ["mcpServer/elicitation/request", "brokered_interaction"],
      ["item/permissions/requestApproval", "brokered_interaction"],
      ["item/tool/call", "internal_host_service"],
      ["account/chatgptAuthTokens/refresh", "internal_host_service"],
      ["attestation/generate", "internal_host_service"],
      ["currentTime/read", "internal_host_service"],
      ["applyPatchApproval", "unsupported"],
      ["execCommandApproval", "unsupported"],
    ]);
    expect(PINNED_CODEX_SERVER_REQUEST_SCHEMA_DIGEST).toBe(
      "1c5837adbfbdd005f387478ba87840808d1353b47b82dcf63739a78bb1c8d3be",
    );
    expect(() => assertPinnedCodexServerRequestMatrix()).not.toThrow();
    expect(codexServerRequestDisposition("future/request")).toBeNull();
  });

  test("parses every brokered method into a bounded display and exact private authority", () => {
    for (const [method, params] of Object.entries(brokeredFixtures) as [BrokeredCodexServerRequestMethod, unknown][]) {
      if (method === "item/fileChange/requestApproval") continue;
      const parsed = parseBrokeredCodexServerRequest({
        authority: { profileId: "profile-a", processGeneration: 9 },
        connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
        requestId: { type: "string", value: method },
        method,
        params,
      });
      expect(parsed.provider).toMatchObject({
        profileId: "profile-a",
        processGeneration: 9,
        method,
        requestId: { type: "string", value: method },
      });
      expect(parsed.provider.requestDigest).toMatch(/^[a-f0-9]{64}$/u);
      expect(JSON.stringify(parsed.display)).not.toContain("git push origin main");
    }

    expect(() => parseBrokeredCodexServerRequest({
      authority: { profileId: "profile-a", processGeneration: 9 },
      connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
      requestId: { type: "string", value: "file" },
      method: "item/fileChange/requestApproval",
      params: brokeredFixtures["item/fileChange/requestApproval"],
    })).toThrow(expect.objectContaining({ code: "UNSUPPORTED_CAPABILITY" }));

    const urlSecret = "URL_SECRET_SENTINEL";
    try {
      parseBrokeredCodexServerRequest({
        authority: { profileId: "profile-a", processGeneration: 9 },
        connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
        requestId: { type: "string", value: "url-elicitation" },
        method: "mcpServer/elicitation/request",
        params: {
          threadId: "thread-1",
          turnId: "turn-1",
          serverName: "example",
          mode: "url",
          _meta: null,
          message: "Authorize Example",
          url: `https://example.com/oauth?access_token=${urlSecret}#${urlSecret}`,
          elicitationId: "elicit-url",
        },
      });
      throw new Error("Expected URL elicitation to be rejected.");
    } catch (error: unknown) {
      expect(error).toBeInstanceOf(CodexError);
      expect((error as CodexError).code).toBe("UNSUPPORTED_CAPABILITY");
      expect((error as Error).message).not.toContain(urlSecret);
    }
    const secretCommand = parseBrokeredCodexServerRequest({
      authority: { profileId: "profile-a", processGeneration: 9 },
      connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
      requestId: { type: "number", value: 99 },
      method: "item/commandExecution/requestApproval",
      params: {
        ...(brokeredFixtures["item/commandExecution/requestApproval"] as Record<string, unknown>),
        command: "git -c credential.helper=SECRET push origin main",
      },
    });
    expect(secretCommand.display).toMatchObject({ commandClass: "git push" });
    expect(JSON.stringify(secretCommand.display)).not.toContain("SECRET");
    expect(secretCommand.privateApprovalAuthority).toMatchObject({
      kind: "command_approval",
      command: "git -c credential.helper=SECRET push origin main",
      reason: "network",
      availableDecisions: ["accept", "acceptForSession", "decline", "cancel"],
      commandActions: [{ type: "unknown", command: "git push origin main" }],
      networkApprovalContext: { host: "github.com", protocol: "https" },
      additionalPermissions: { network: { enabled: true } },
    });

    const reset = (command: string) => parseBrokeredCodexServerRequest({
      authority: { profileId: "profile-a", processGeneration: 9 },
      connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
      requestId: { type: "string", value: command },
      method: "item/commandExecution/requestApproval",
      params: {
        ...(brokeredFixtures["item/commandExecution/requestApproval"] as Record<string, unknown>),
        command,
      },
    });
    const hard = reset("git reset --hard HEAD");
    const soft = reset("git reset --soft HEAD^");
    expect(hard.display).toEqual(soft.display);
    expect(hard.privateApprovalAuthority).not.toEqual(soft.privateApprovalAuthority);

    const permission = parseBrokeredCodexServerRequest({
      authority: { profileId: "profile-a", processGeneration: 9 },
      connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
      requestId: { type: "string", value: "permission" },
      method: "item/permissions/requestApproval",
      params: brokeredFixtures["item/permissions/requestApproval"],
    });
    expect(permission.privateApprovalAuthority).toEqual({
      kind: "permission_approval",
      permissions: {
        fileSystem: { read: [permissionPrivatePath] },
        network: { enabled: true },
      },
      reason: "network",
      workingDirectory: "/workspace",
      environmentId: null,
    });
    expect(JSON.stringify(permission.display)).not.toContain(permissionPrivatePath);
    for (const invalidCwd of [undefined, null, "relative/workspace"] as const) {
      const params: Record<string, unknown> = {
        ...(brokeredFixtures["item/permissions/requestApproval"] as Record<string, unknown>),
      };
      if (invalidCwd === undefined) delete params.cwd;
      else params.cwd = invalidCwd;
      expect(() => parseBrokeredCodexServerRequest({
        authority: { profileId: "profile-a", processGeneration: 9 },
        connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
        requestId: { type: "string", value: `permission-cwd-${String(invalidCwd)}` },
        method: "item/permissions/requestApproval",
        params,
      })).toThrow(CodexError);
    }

    expect(() => reset("   ")).toThrow(expect.objectContaining({
      code: "UNSUPPORTED_CAPABILITY",
    }));
  });

  test("preserves the exact representable command approval decisions and rejects unsupported contracts", () => {
    const parseCommand = (availableDecisions: unknown, includeDecisions = true) => {
      const params = {
        ...(brokeredFixtures["item/commandExecution/requestApproval"] as Record<string, unknown>),
        ...(includeDecisions ? { availableDecisions } : {}),
      };
      if (!includeDecisions) delete params.availableDecisions;
      return parseBrokeredCodexServerRequest({
        authority: { profileId: "profile-a", processGeneration: 9 },
        connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
        requestId: { type: "string", value: "command-decisions" },
        method: "item/commandExecution/requestApproval",
        params,
      });
    };
    const amendment = {
      acceptWithExecpolicyAmendment: {
        execpolicy_amendment: { safeOpaqueProviderValue: true },
      },
    };

    const acceptAndCancel = parseCommand(["accept", "cancel", "accept"]);
    expect(acceptAndCancel.display).toMatchObject({
      kind: "command_approval",
      availableDecisions: ["once", "cancel"],
    });
    expect(compileCodexInteractionResponse({
      method: "item/commandExecution/requestApproval",
      kind: acceptAndCancel.kind,
      privateParams: acceptAndCancel.privateParams,
      resolution: { kind: "approval_decision", decision: "once" },
    })).toEqual({ decision: "accept" });
    expect(compileCodexInteractionResponse({
      method: "item/commandExecution/requestApproval",
      kind: acceptAndCancel.kind,
      privateParams: acceptAndCancel.privateParams,
      resolution: { kind: "approval_decision", decision: "cancel" },
    })).toEqual({ decision: "cancel" });
    for (const unavailable of ["session", "decline"] as const) {
      expect(() => compileCodexInteractionResponse({
        method: "item/commandExecution/requestApproval",
        kind: acceptAndCancel.kind,
        privateParams: acceptAndCancel.privateParams,
        resolution: { kind: "approval_decision", decision: unavailable },
      })).toThrow("does not offer");
    }

    const rejectionOnly = parseCommand([amendment, "decline", "cancel"]);
    expect(rejectionOnly.display).toMatchObject({
      kind: "command_approval",
      availableDecisions: ["decline", "cancel"],
    });

    const full = parseCommand(["accept", "acceptForSession", "decline", "cancel"]);
    expect(full.display).toMatchObject({
      kind: "command_approval",
      availableDecisions: ["once", "session", "decline", "cancel"],
    });
    for (const [decision, providerDecision] of [
      ["once", "accept"],
      ["session", "acceptForSession"],
      ["decline", "decline"],
      ["cancel", "cancel"],
    ] as const) {
      expect(compileCodexInteractionResponse({
        method: "item/commandExecution/requestApproval",
        kind: full.kind,
        privateParams: full.privateParams,
        resolution: { kind: "approval_decision", decision },
      })).toEqual({ decision: providerDecision });
    }

    for (const [availableDecisions, includeDecisions] of [
      [undefined, false],
      [null, true],
      [[], true],
      [[amendment], true],
      [["futureDecision", "cancel"], true],
      [[{ unexpectedAmendment: {} }, "cancel"], true],
    ] as const) {
      try {
        parseCommand(availableDecisions, includeDecisions);
        throw new Error("Expected the command decision contract to be rejected.");
      } catch (error: unknown) {
        expect(error).toBeInstanceOf(CodexError);
        expect((error as CodexError).code).toBe("UNSUPPORTED_CAPABILITY");
      }
    }
  });

  test("rejects ambiguous user-input question IDs and rendered option labels", () => {
    const parseQuestions = (questions: unknown) => parseBrokeredCodexServerRequest({
      authority: { profileId: "profile-a", processGeneration: 9 },
      connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
      requestId: { type: "string", value: "ambiguous-questions" },
      method: "item/tool/requestUserInput",
      params: {
        ...(brokeredFixtures["item/tool/requestUserInput"] as Record<string, unknown>),
        questions,
      },
    });
    const question = {
      id: "confirm",
      header: "Confirm",
      question: "Continue?",
      isOther: false,
      isSecret: false,
      options: [{ label: "Yes", description: "Continue" }],
    };
    expect(() => parseQuestions([
      question,
      { ...question, header: "Confirm again", question: "Really continue?" },
    ])).toThrow("question ids must be unique");
    expect(() => parseQuestions([{
      ...question,
      options: [
        { label: "same", description: "First meaning" },
        { label: "same", description: "Second meaning" },
      ],
    }])).toThrow("option labels must be unique");
    expect(() => parseQuestions([{
      ...question,
      options: [
        { label: "\u0001", description: "First control" },
        { label: "\u0002", description: "Second control" },
      ],
    }])).toThrow("option labels must be unique");
  });

  test("caps valid provider auto-resolution intervals and rejects malformed authority", () => {
    const parseTimeout = (autoResolutionMs: unknown): number =>
      parseBrokeredCodexServerRequest({
        authority: { profileId: "profile-a", processGeneration: 1 },
        connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
        requestId: { type: "string", value: `timeout-${String(autoResolutionMs)}` },
        method: "item/tool/requestUserInput",
        params: { ...(brokeredFixtures["item/tool/requestUserInput"] as Record<string, unknown>), autoResolutionMs },
      }).timeoutMs;
    expect(parseTimeout(null)).toBe(INTERACTION_MAX_PENDING_MS);
    expect(parseTimeout(0)).toBe(0);
    expect(parseTimeout(1)).toBe(1);
    expect(parseTimeout(INTERACTION_MAX_PENDING_MS)).toBe(INTERACTION_MAX_PENDING_MS);
    expect(parseTimeout(INTERACTION_MAX_PENDING_MS + 1)).toBe(INTERACTION_MAX_PENDING_MS);
    for (const malformed of [-1, 1.5, Number.NaN, "1000"]) {
      expect(() => parseTimeout(malformed)).toThrow(CodexError);
    }
  });

  test("keeps numeric and string request identities distinct and rejects permission escalation", () => {
    expect(parseProviderRequestId(1)).toEqual({ type: "number", value: 1 });
    expect(parseProviderRequestId("1")).toEqual({ type: "string", value: "1" });
    const parsed = parseBrokeredCodexServerRequest({
      authority: { profileId: "profile-a", processGeneration: 1 },
      connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
      requestId: { type: "number", value: 1 },
      method: "item/permissions/requestApproval",
      params: brokeredFixtures["item/permissions/requestApproval"],
    });
    expect(parsed.display).toMatchObject({
      kind: "permission_approval",
      requested: [{ name: "fileSystem" }, { name: "network" }],
    });
    expect(JSON.stringify(parsed.display)).not.toContain("PERMISSION_VALUE_SENTINEL");
    expect(JSON.stringify(parsed.display)).not.toContain(permissionPrivatePath);
    expect(() => compileCodexInteractionResponse({
      method: "item/permissions/requestApproval",
      kind: parsed.kind,
      privateParams: parsed.privateParams,
      resolution: {
        kind: "permission_grant",
        permissions: ["network", "notRequested"],
        scope: "session",
      },
    })).toThrow("exceed");
    expect(compileCodexInteractionResponse({
      method: "item/permissions/requestApproval",
      kind: parsed.kind,
      privateParams: parsed.privateParams,
      resolution: { kind: "approval_decision", decision: "decline" },
    })).toEqual({ permissions: {}, scope: "turn" });
    expect(() => compileCodexInteractionResponse({
      method: "item/permissions/requestApproval",
      kind: parsed.kind,
      privateParams: parsed.privateParams,
      resolution: { kind: "approval_decision", decision: "cancel" },
    })).toThrow("supports");
    expect(compileCodexInteractionResponse({
      method: "item/permissions/requestApproval",
      kind: parsed.kind,
      privateParams: parsed.privateParams,
      resolution: {
        kind: "permission_grant",
        permissions: ["network"],
        scope: "turn",
      },
    })).toEqual({ permissions: { network: { enabled: true } }, scope: "turn" });
    expect(compileCodexInteractionResponse({
      method: "item/permissions/requestApproval",
      kind: parsed.kind,
      privateParams: parsed.privateParams,
      resolution: {
        kind: "permission_grant",
        permissions: ["fileSystem"],
        scope: null,
      },
    })).toEqual({
      permissions: { fileSystem: { read: [permissionPrivatePath] } },
      scope: "turn",
    });
  });

  test("brokers the closed standard MCP form contract and validates the exact protected response", () => {
    const schemaOnlySentinel = "MCP_SCHEMA_PRIVATE_SENTINEL";
    const params = {
      threadId: "thread-1",
      turnId: "turn-1",
      serverName: "example",
      mode: "form",
      _meta: null,
      message: "Configure Example",
      requestedSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        type: "object",
        properties: {
          birthday: { type: "string", format: "date" },
          email: {
            type: "string",
            title: schemaOnlySentinel,
            description: schemaOnlySentinel,
            minLength: 3,
            maxLength: 320,
            format: "email",
            default: "default@example.com",
          },
          retries: { type: "integer", minimum: 1, maximum: 5, default: 2 },
          ratio: { type: "number", minimum: 0, maximum: 1 },
          confirmed: { type: "boolean", default: false },
          endpoint: { type: "string", format: "uri" },
          tier: {
            type: "string",
            oneOf: [
              { const: "free", title: schemaOnlySentinel },
              { const: "pro", title: schemaOnlySentinel },
            ],
            default: "free",
          },
          tags: {
            type: "array",
            minItems: 1,
            maxItems: 2,
            items: {
              anyOf: [
                { const: "stable", title: schemaOnlySentinel },
                { const: "fast", title: schemaOnlySentinel },
              ],
            },
            default: ["stable"],
          },
          when: { type: "string", format: "date-time" },
        },
        required: ["email", "retries", "confirmed", "tier", "tags"],
      },
    };
    const parsed = parseBrokeredCodexServerRequest({
      authority: { profileId: "profile-a", processGeneration: 1 },
      connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
      requestId: { type: "string", value: "mcp-form" },
      method: "mcpServer/elicitation/request",
      params,
    });
    expect(parsed.display).toEqual({
      kind: "mcp_elicitation",
      summary: "Configure Example",
      serverName: "example",
      mode: "form",
      url: null,
      mayContainSecrets: true,
      fields: [
        { name: "birthday", type: "string", required: false, minLength: 0, maxLength: 16_384, format: "date" },
        { name: "confirmed", type: "boolean", required: true },
        { name: "email", type: "string", required: true, minLength: 3, maxLength: 320, format: "email" },
        { name: "endpoint", type: "string", required: false, minLength: 0, maxLength: 16_384, format: "uri" },
        { name: "ratio", type: "number", required: false, minimum: 0, maximum: 1 },
        { name: "retries", type: "integer", required: true, minimum: 1, maximum: 5 },
        { name: "tags", type: "multi_select", required: true, choices: ["stable", "fast"], minItems: 1, maxItems: 2 },
        { name: "tier", type: "single_select", required: true, choices: ["free", "pro"] },
        { name: "when", type: "string", required: false, minLength: 0, maxLength: 16_384, format: "date-time" },
      ],
    });
    expect(JSON.stringify(parsed.display)).not.toContain(schemaOnlySentinel);
    const content = {
      birthday: "2024-02-29",
      email: "person@example.com",
      endpoint: "https://example.com/configure",
      retries: 3,
      ratio: 0.5,
      confirmed: true,
      tier: "pro",
      tags: ["stable", "fast"],
      when: "2026-08-23T04:05:06Z",
    };
    expect(compileCodexInteractionResponse({
      method: "mcpServer/elicitation/request",
      kind: parsed.kind,
      privateParams: parsed.privateParams,
      resolution: { kind: "mcp_submission", action: "accept", content },
    })).toEqual({ action: "accept", content, _meta: null });
    expect(compileCodexInteractionResponse({
      method: "mcpServer/elicitation/request",
      kind: parsed.kind,
      privateParams: parsed.privateParams,
      resolution: { kind: "mcp_submission", action: "decline" },
    })).toEqual({ action: "decline", content: null, _meta: null });

    const submittedSentinel = "MCP_SUBMISSION_SECRET_SENTINEL";
    for (const invalid of [
      { ...content, email: submittedSentinel },
      { ...content, email: "a..b@example..com" },
      { ...content, birthday: "2025-02-29" },
      { ...content, endpoint: "/relative/path" },
      { ...content, when: "2026-08-23T25:05:06Z" },
      { ...content, retries: 2.5 },
      { ...content, retries: 6 },
      { ...content, tier: submittedSentinel },
      { ...content, tags: [submittedSentinel] },
      { ...content, additional: submittedSentinel },
      { retries: 3, confirmed: true, tier: "pro", tags: ["stable"] },
      null,
    ]) {
      const error = (() => {
        try {
          compileCodexInteractionResponse({
            method: "mcpServer/elicitation/request",
            kind: parsed.kind,
            privateParams: parsed.privateParams,
            resolution: { kind: "mcp_submission", action: "accept", content: invalid },
          });
          return null;
        } catch (caught: unknown) {
          return caught;
        }
      })();
      expect(error).toBeInstanceOf(CodexError);
      expect((error as CodexError).code).toBe("INVALID_INPUT");
      expect((error as Error).message).not.toContain(submittedSentinel);
    }
  });

  test("fails closed on opaque, malformed, oversized, and lookalike MCP form schemas", () => {
    const schemaSentinel = "MCP_UNSUPPORTED_SCHEMA_SENTINEL";
    const base = {
      threadId: "thread-1",
      turnId: "turn-1",
      serverName: "example",
      _meta: null,
      message: "Configure Example",
    };
    const unsupported = [
      {
        ...base,
        mode: "form",
        requestedSchema: null,
      },
      {
        ...base,
        mode: "openai/form",
        requestedSchema: { type: "object", properties: { secret: { type: schemaSentinel } } },
      },
      {
        ...base,
        mode: "form",
        requestedSchema: {
          type: "object",
          properties: { token: { type: "string", pattern: schemaSentinel } },
        },
      },
      {
        ...base,
        mode: "form",
        _meta: {
          codex_approval_kind: "tool_suggestion",
          persist: "always",
          tool_type: "plugin",
          suggest_type: "install",
          install_url: `https://example.com/install?secret=${schemaSentinel}`,
        },
        requestedSchema: { type: "object", properties: {} },
      },
      {
        ...base,
        mode: "form",
        _meta: {
          codex_approval_kind: "mcp_tool_call",
          codex_request_type: "approval_request",
          connector_name: schemaSentinel,
          tool_name: "delete_records",
          tool_params: { target: schemaSentinel },
          persist: "always",
        },
        requestedSchema: { type: "object", properties: {} },
      },
      {
        ...base,
        mode: "form",
        _meta: { codex_approval_kind: "future_side_effect", detail: schemaSentinel },
        requestedSchema: { type: "object", properties: {} },
      },
      {
        ...base,
        mode: "form",
        requestedSchema: { Type: "object", properties: {} },
      },
      {
        ...base,
        mode: "form",
        requestedSchema: {
          type: "object",
          properties: Object.fromEntries(Array.from({ length: 17 }, (_, index) => [
            `field_${String(index)}`,
            { type: "boolean" },
          ])),
        },
      },
      {
        ...base,
        mode: "form",
        requestedSchema: {
          type: "object",
          properties: { choice: { type: "string", enum: ["x".repeat(129)] } },
        },
      },
    ];
    for (const [index, params] of unsupported.entries()) {
      const error = (() => {
        try {
          parseBrokeredCodexServerRequest({
            authority: { profileId: "profile-a", processGeneration: 1 },
            connectionId: "018f1f55-3f10-7c1a-8f7b-c6dc608bcd3b",
            requestId: { type: "string", value: `unsupported-${String(index)}` },
            method: "mcpServer/elicitation/request",
            params,
          });
          return null;
        } catch (caught: unknown) {
          return caught;
        }
      })();
      expect(error).toBeInstanceOf(CodexError);
      expect((error as Error).message).not.toContain(schemaSentinel);
      expect(JSON.stringify(error)).not.toContain(schemaSentinel);
    }
  });

  test("projects visible deltas and metrics while excluding raw reasoning and tool payloads", () => {
    expect(parseFact("item/agentMessage/delta", {
      threadId: "thread-1", turnId: "turn-1", itemId: "item-1", delta: "hello",
    })).toMatchObject({ type: "assistantDelta", text: "hello" });
    expect(parseFact("item/reasoning/summaryTextDelta", {
      threadId: "thread-1", turnId: "turn-1", itemId: "item-2", summaryIndex: 0, delta: "summary",
    })).toMatchObject({ type: "reasoningSummaryDelta", text: "summary", summaryIndex: 0 });
    const hidden = parseFact("item/reasoning/textDelta", {
      threadId: "thread-1", turnId: "turn-1", itemId: "item-2", contentIndex: 0,
      delta: "hidden chain of thought",
    });
    expect(hidden).toEqual({ type: "notificationIgnored", method: "item/reasoning/textDelta" });
    expect(JSON.stringify(hidden)).not.toContain("hidden chain of thought");

    const output = parseFact("item/commandExecution/outputDelta", {
      threadId: "thread-1", turnId: "turn-1", itemId: "item-3", delta: "SECRET OUTPUT",
    });
    expect(output).toMatchObject({ type: "toolProgress", toolKind: "command", outputBytesObserved: 13 });
    expect(JSON.stringify(output)).not.toContain("SECRET OUTPUT");

    const item = parseFact("item/completed", {
      threadId: "thread-1", turnId: "turn-1", completedAtMs: 2,
      item: {
        type: "mcpToolCall", id: "item-4", server: "github", tool: "create_issue",
        status: "completed", arguments: { token: "SECRET" }, result: { content: "SECRET RESULT" },
      },
    });
    expect(item).toMatchObject({ type: "itemCompleted", server: "github", tool: "create_issue", status: "completed" });
    expect(JSON.stringify(item)).not.toContain("SECRET");

    const diagnosticPath = ["", "Users", "alice", "private", "key"].join("/");
    const diagnosticSecret = `Bearer PROVIDER_DIAGNOSTIC_SECRET at ${diagnosticPath}`;
    const warning = parseFact("warning", { threadId: "thread-1", message: diagnosticSecret });
    const error = parseFact("error", {
      threadId: "thread-1",
      turnId: "turn-1",
      willRetry: false,
      error: { message: diagnosticSecret, codexErrorInfo: diagnosticSecret },
    });
    expect(warning).toMatchObject({ code: "provider_warning", message: "Codex reported a provider warning." });
    expect(error).toMatchObject({ code: "provider_error", message: "Codex reported a provider error." });
    expect(JSON.stringify([warning, error])).not.toContain("PROVIDER_DIAGNOSTIC_SECRET");
    expect(JSON.stringify([warning, error])).not.toContain(diagnosticPath);
  });

  test("reduces plan, diff, and token notifications without retaining patch text", () => {
    expect(parseFact("turn/plan/updated", {
      threadId: "thread-1", turnId: "turn-1", explanation: "Next", plan: [
        { step: "Inspect", status: "completed" },
        { step: "Fix", status: "inProgress" },
      ],
    })).toMatchObject({ type: "planUpdated", steps: [{ text: "Inspect", status: "completed" }, { text: "Fix", status: "in_progress" }] });
    const diff = parseFact("turn/diff/updated", {
      threadId: "thread-1", turnId: "turn-1", diff: "diff --git a/a b/a\n+SECRET\n",
    });
    expect(diff).toMatchObject({ type: "diffUpdated", changedFiles: 1 });
    expect(JSON.stringify(diff)).not.toContain("SECRET");
    expect(parseFact("thread/tokenUsage/updated", {
      threadId: "thread-1", turnId: "turn-1",
      tokenUsage: {
        total: { totalTokens: 15, inputTokens: 10, cachedInputTokens: 3, cacheWriteInputTokens: 0, outputTokens: 5, reasoningOutputTokens: 2 },
        last: { totalTokens: 15, inputTokens: 10, cachedInputTokens: 3, cacheWriteInputTokens: 0, outputTokens: 5, reasoningOutputTokens: 2 },
        modelContextWindow: 200_000,
      },
    })).toMatchObject({ type: "tokenUsageUpdated", totalTokens: 15, reasoningOutputTokens: 2, modelContextWindow: 200_000 });
  });

  test("projects an exact non-secret live command digest and no arbitrary command oracle", () => {
    const command = "/bin/echo hra-live-tool-progress | /usr/bin/tee ./.hra-live-command-proof-00000000-0000-4000-8000-000000000001.txt";
    const expectedDigest = createHash("sha256")
      .update("hra:live-acceptance-command:v1\0", "utf8")
      .update(command, "utf8")
      .digest("hex");
    expect(safeLiveAcceptanceCommandDigest(command)).toBe(expectedDigest);
    expect(parseFact("item/started", {
      threadId: "thread-1",
      turnId: "turn-1",
      item: {
        type: "commandExecution",
        id: "command-1",
        command,
        cwd: "/workspace",
        status: "inProgress",
      },
    })).toMatchObject({
      type: "itemStarted",
      itemKind: "commandExecution",
      liveAcceptanceCommandDigest: expectedDigest,
    });
    expect(parseFact("item/completed", {
      threadId: "thread-1",
      turnId: "turn-1",
      item: {
        type: "commandExecution",
        id: "command-1",
        command,
        cwd: "/workspace",
        status: "completed",
      },
    })).toMatchObject({
      type: "itemCompleted",
      itemKind: "commandExecution",
      liveAcceptanceCommandDigest: expectedDigest,
    });

    const secret = "TOKEN=private /bin/sh -c 'do-sensitive-work'";
    const arbitrary = parseFact("item/started", {
      threadId: "thread-1",
      turnId: "turn-1",
      item: {
        type: "commandExecution",
        id: "command-2",
        command: secret,
        cwd: "/workspace",
        status: "inProgress",
      },
    });
    expect(safeLiveAcceptanceCommandDigest(secret)).toBeUndefined();
    expect(arbitrary).not.toHaveProperty("liveAcceptanceCommandDigest");
    expect(JSON.stringify(arbitrary)).not.toContain("private");
    for (const lookalike of [
      `${command} `,
      command.replace("/bin/echo", "echo"),
      command.replace("hra-live-tool-progress", "other"),
      command.replace(".hra-live-command-proof-", ".other-"),
      command.replace("00000000-0000-4000-8000-000000000001", "NOT-A-UUID"),
    ]) expect(safeLiveAcceptanceCommandDigest(lookalike)).toBeUndefined();
  });
});

describe("runtime capability resolution", () => {
  test("maps only the advertised reduced presets", () => {
    expect(resolvePreset(capabilities, "low", false)).toMatchObject({
      model: "gpt-5.6-luna",
      effort: "max",
      serviceTier: null,
    });
    expect(resolvePreset(capabilities, "high", true)).toMatchObject({
      model: "gpt-5.6-sol",
      effort: "max",
      serviceTier: "priority",
    });
    expect(resolvePreset(capabilities, "ultra", false)).toMatchObject({
      model: "gpt-5.6-sol",
      effort: "ultra",
    });
  });

  test("fails closed when Fast is not advertised", () => {
    const withoutFast: CodexCapabilitySnapshot = {
      ...capabilities,
      models: capabilities.models.map((model) => ({ ...model, serviceTiers: [] })),
    };
    expect(() => resolvePreset(withoutFast, "high", true)).toThrow(CodexError);
  });

  test("never selects a prefixed or suffixed lookalike under catalog reordering", () => {
    const catalog = [
      { ...capabilities.models[0]!, id: "gpt-5.6-luna-mini", model: "gpt-5.6-luna-mini" },
      { ...capabilities.models[1]!, id: "legacy-gpt-5.6-sol", model: "legacy-gpt-5.6-sol" },
      ...capabilities.models,
    ];
    fc.assert(fc.property(fc.shuffledSubarray(catalog, { minLength: 4, maxLength: 4 }), (models) => {
      expect(resolvePreset({ ...capabilities, models }, "low", false).model).toBe("gpt-5.6-luna");
      expect(resolvePreset({ ...capabilities, models }, "high", false).model).toBe("gpt-5.6-sol");
    }));
    const lookalikesOnly = {
      ...capabilities,
      models: capabilities.models.map((model) => ({ ...model, model: `${model.model}-mini` })),
    };
    expect(() => resolvePreset(lookalikesOnly, "high", false)).toThrow(CodexError);
  });

  test("rejects an unrecognized reasoning effort", () => {
    expect(() =>
      parseModelPage({
        data: [
          {
            id: "future",
            model: "future",
            displayName: "Future",
            hidden: false,
            supportedReasoningEfforts: [{ reasoningEffort: "unbounded" }],
            defaultReasoningEffort: "unbounded",
            serviceTiers: [],
            defaultServiceTier: null,
            isDefault: false,
          },
        ],
        nextCursor: null,
      }),
    ).toThrow(CodexError);
  });

  test("parses bounded usage without accepting lossy integers", () => {
    expect(
      parseAccountUsage({
        summary: {
          lifetimeTokens: 42,
          peakDailyTokens: 12,
          longestRunningTurnSec: null,
          currentStreakDays: 3,
          longestStreakDays: 5,
        },
        dailyUsageBuckets: [{ startDate: "2026-08-22", tokens: 9 }],
      }),
    ).toEqual({
      summary: {
        lifetimeTokens: 42,
        peakDailyTokens: 12,
        longestRunningTurnSec: null,
        currentStreakDays: 3,
        longestStreakDays: 5,
      },
      dailyUsageBuckets: [{ startDate: "2026-08-22", tokens: 9 }],
    });
    expect(() =>
      parseAccountUsage({
        summary: {
          lifetimeTokens: Number.MAX_SAFE_INTEGER + 1,
          peakDailyTokens: null,
          longestRunningTurnSec: null,
          currentStreakDays: null,
          longestStreakDays: null,
        },
        dailyUsageBuckets: null,
      }),
    ).toThrow(CodexError);
  });

  test("parses the pinned paginated turn and item response envelopes", () => {
    const turn = {
      id: "turn-1",
      items: [],
      status: "completed" as const,
      startedAt: 1,
      completedAt: 2,
      durationMs: 1_000,
    };
    expect(parseThreadTurnsPage({ data: [turn], nextCursor: "older", backwardsCursor: "newer" }))
      .toEqual({ data: [turn], nextCursor: "older", backwardsCursor: "newer" });
    expect(parseThreadItemsPage({
      data: [
        { turnId: "turn-1", item: { type: "userMessage", id: "item-user", clientId: "client-exact", content: [{ type: "text", text: "hello" }] } },
        { turnId: "turn-1", item: { type: "agentMessage", id: "item-1", text: "hello" } },
      ],
      nextCursor: null,
      backwardsCursor: "back",
    })).toEqual({
      data: [
        { turnId: "turn-1", item: { type: "userMessage", id: "item-user", clientId: "client-exact", text: ["hello"] } },
        { turnId: "turn-1", item: { type: "agentMessage", id: "item-1", text: "hello" } },
      ],
      nextCursor: null,
      backwardsCursor: "back",
    });
  });

  test("rejects provider turns at the metadata-only thread boundary", () => {
    expect(() => parseThreadMetadataRead({ thread: { turns: [{}] } })).toThrow(CodexError);
  });
});
