import { z } from "@hra-internal/schema";

import {
  agentIdSchema,
  repositoryIdSchema,
  taskReferenceIdSchema,
  type TaskKey,
} from "./model";
import {
  createAgentEnrollmentEnvelopeSchema,
  createAgentEnrollmentRequestSchema,
  createAgentEnvelopeSchema,
  createAgentRequestSchema,
  createOrganizationEnvelopeSchema,
  createOrganizationRequestSchema,
  createWorkspaceEnvelopeSchema,
  createWorkspaceRequestSchema,
  disableAgentEnvelopeSchema,
  disableAgentRequestSchema,
  getAgentEnvelopeSchema,
  getAgentQuerySchema,
  listAgentCredentialsEnvelopeSchema,
  listAgentCredentialsQuerySchema,
  listAgentSessionsEnvelopeSchema,
  listAgentSessionsQuerySchema,
  listAgentsEnvelopeSchema,
  listAgentsQuerySchema,
  listOrganizationsEnvelopeSchema,
  listOrganizationsQuerySchema,
  listWorkspacesEnvelopeSchema,
  listWorkspacesQuerySchema,
  refreshAuthEnvelopeSchema,
  refreshAuthRequestSchema,
  revokeAgentCredentialEnvelopeSchema,
  revokeAgentCredentialRequestSchema,
} from "./human";
import { locatorSchema } from "./tokens";
import {
  acceptTaskRequestSchema,
  acceptTaskEnvelopeSchema,
  addTaskCommentEnvelopeSchema,
  addTaskCommentRequestSchema,
  addTaskReferenceRequestSchema,
  assignTaskRequestSchema,
  blockedTasksEnvelopeSchema,
  blockedTasksQuerySchema,
  cancelTaskRequestSchema,
  claimTaskEnvelopeSchema,
  claimTaskRequestSchema,
  clearTaskParentRequestSchema,
  contextEnvelopeSchema,
  createWorkspaceRepositoryRequestSchema,
  createTaskEnvelopeSchema,
  createTaskRequestSchema,
  deferTaskRequestSchema,
  getTaskEnvelopeSchema,
  listTaskCommentsEnvelopeSchema,
  listTaskCommentsQuerySchema,
  listTaskDependenciesEnvelopeSchema,
  listTaskDependenciesQuerySchema,
  listTaskEventsEnvelopeSchema,
  listTaskEventsQuerySchema,
  listTaskLabelsEnvelopeSchema,
  listTaskReferencesEnvelopeSchema,
  listTaskReferencesQuerySchema,
  listTasksEnvelopeSchema,
  listTasksQuerySchema,
  listWorkspaceRepositoriesEnvelopeSchema,
  listWorkspaceRepositoriesQuerySchema,
  readyTasksEnvelopeSchema,
  readyTasksQuerySchema,
  redeemEnrollmentEnvelopeSchema,
  redeemEnrollmentRequestSchema,
  rejectTaskRequestSchema,
  rejectTaskEnvelopeSchema,
  releaseClaimEnvelopeSchema,
  releaseClaimRequestSchema,
  removeTaskReferenceEnvelopeSchema,
  removeTaskReferenceRequestSchema,
  removeWorkspaceRepositoryEnvelopeSchema,
  removeWorkspaceRepositoryRequestSchema,
  reopenTaskRequestSchema,
  reviewQueueEnvelopeSchema,
  reviewQueueQuerySchema,
  renewClaimEnvelopeSchema,
  renewClaimRequestSchema,
  setTaskParentRequestSchema,
  startSessionEnvelopeSchema,
  startSessionRequestSchema,
  submitTaskEnvelopeSchema,
  submitTaskRequestSchema,
  taskDependencyMutationEnvelopeSchema,
  taskDependencyMutationRequestSchema,
  taskGraphEnvelopeSchema,
  taskGraphQuerySchema,
  taskLabelMutationRequestSchema,
  taskMutationEnvelopeSchema,
  taskReferenceEnvelopeSchema,
  taskRouteParamsSchema,
  updateTaskRequestSchema,
  workspaceRepositoryEnvelopeSchema,
} from "./wire";

export const taskctlHeaders = {
  authorization: "Authorization",
  contentType: "Content-Type",
  idempotencyKey: "Idempotency-Key",
  session: "X-Taskctl-Session",
} as const;

export const agentRouteParamsSchema = z.object({ agentId: agentIdSchema }).strict();
export const agentCredentialRouteParamsSchema = z
  .object({ agentId: agentIdSchema, credentialId: locatorSchema })
  .strict();
export const repositoryRouteParamsSchema = z.object({ repositoryId: repositoryIdSchema }).strict();
export const taskReferenceRouteParamsSchema = z
  .object({ key: taskRouteParamsSchema.shape.key, referenceId: taskReferenceIdSchema })
  .strict();

function agentPath(agentId: string): string {
  return `/v1/agents/${encodeURIComponent(agentRouteParamsSchema.parse({ agentId }).agentId)}`;
}

function agentEnrollmentPath(agentId: string): string {
  return `${agentPath(agentId)}/enrollments`;
}

function agentCredentialsPath(agentId: string): string {
  return `${agentPath(agentId)}/credentials`;
}

function agentCredentialRevokePath(agentId: string, credentialId: string): string {
  const parsed = agentCredentialRouteParamsSchema.parse({ agentId, credentialId });
  return `${agentCredentialsPath(parsed.agentId)}/${encodeURIComponent(parsed.credentialId)}/revoke`;
}

function taskPath(key: TaskKey): string {
  return `/v1/tasks/${encodeURIComponent(taskRouteParamsSchema.parse({ key }).key)}`;
}

function taskActionPath(key: TaskKey, action: string): string {
  return `${taskPath(key)}/${action}`;
}

function repositoryRemovePath(repositoryId: string): string {
  const parsed = repositoryRouteParamsSchema.parse({ repositoryId });
  return `/v1/workspace/repositories/${encodeURIComponent(parsed.repositoryId)}/remove`;
}

function taskReferenceRemovePath(key: TaskKey, referenceId: string): string {
  const parsed = taskReferenceRouteParamsSchema.parse({ key, referenceId });
  return `${taskPath(parsed.key)}/references/${encodeURIComponent(parsed.referenceId)}/remove`;
}

export const taskctlApiRoutes = {
  refreshAuth: "/v1/auth/refresh",
  organizations: "/v1/organizations",
  workspaces: "/v1/workspaces",
  agents: "/v1/agents",
  agent: agentPath,
  agentEnrollments: agentEnrollmentPath,
  agentCredentials: agentCredentialsPath,
  agentCredentialRevoke: agentCredentialRevokePath,
  agentSessions: (agentId: string): string => `${agentPath(agentId)}/sessions`,
  agentDisable: (agentId: string): string => `${agentPath(agentId)}/disable`,
  redeemEnrollment: "/v1/agent/enrollments/redeem",
  sessions: "/v1/agent/sessions",
  context: "/v1/context",
  tasks: "/v1/tasks",
  readyTasks: "/v1/tasks/ready",
  blockedTasks: "/v1/tasks/blocked",
  reviews: "/v1/reviews",
  workspaceRepositories: "/v1/workspace/repositories",
  workspaceRepositoryRemove: repositoryRemovePath,
  task: taskPath,
  taskUpdate: (key: TaskKey): string => taskActionPath(key, "update"),
  taskCancel: (key: TaskKey): string => taskActionPath(key, "cancel"),
  taskReopen: (key: TaskKey): string => taskActionPath(key, "reopen"),
  taskAssign: (key: TaskKey): string => taskActionPath(key, "assign"),
  taskDefer: (key: TaskKey): string => taskActionPath(key, "defer"),
  taskLabels: (key: TaskKey): string => taskActionPath(key, "labels"),
  taskLabelRemove: (key: TaskKey): string => taskActionPath(key, "labels/remove"),
  taskComments: (key: TaskKey): string => taskActionPath(key, "comments"),
  taskEvents: (key: TaskKey): string => taskActionPath(key, "events"),
  taskGraph: (key: TaskKey): string => taskActionPath(key, "graph"),
  taskDependencies: (key: TaskKey): string => taskActionPath(key, "dependencies"),
  taskDependencyRemove: (key: TaskKey): string => taskActionPath(key, "dependencies/remove"),
  taskParentSet: (key: TaskKey): string => taskActionPath(key, "parent/set"),
  taskParentClear: (key: TaskKey): string => taskActionPath(key, "parent/clear"),
  taskReferences: (key: TaskKey): string => taskActionPath(key, "references"),
  taskReferenceRemove: taskReferenceRemovePath,
  claimTask: (key: TaskKey): string => taskActionPath(key, "claim"),
  renewClaim: (key: TaskKey): string => taskActionPath(key, "claim/renew"),
  releaseClaim: (key: TaskKey): string => taskActionPath(key, "claim/release"),
  submitTask: (key: TaskKey): string => taskActionPath(key, "submit"),
  acceptTask: (key: TaskKey): string => taskActionPath(key, "accept"),
  rejectTask: (key: TaskKey): string => taskActionPath(key, "reject"),
} as const;

export const taskctlApiOperations = {
  refreshAuth: {
    method: "POST",
    path: taskctlApiRoutes.refreshAuth,
    authorization: "human-refresh",
    session: false,
    idempotency: false,
    requestSchema: refreshAuthRequestSchema,
    responseSchema: refreshAuthEnvelopeSchema,
  },
  listOrganizations: {
    method: "GET",
    path: taskctlApiRoutes.organizations,
    authorization: "human-account",
    session: false,
    idempotency: false,
    querySchema: listOrganizationsQuerySchema,
    responseSchema: listOrganizationsEnvelopeSchema,
  },
  createOrganization: {
    method: "POST",
    path: taskctlApiRoutes.organizations,
    authorization: "human-account",
    session: false,
    idempotency: true,
    requestSchema: createOrganizationRequestSchema,
    responseSchema: createOrganizationEnvelopeSchema,
  },
  listWorkspaces: {
    method: "GET",
    path: taskctlApiRoutes.workspaces,
    authorization: "human-organization",
    session: false,
    idempotency: false,
    querySchema: listWorkspacesQuerySchema,
    responseSchema: listWorkspacesEnvelopeSchema,
  },
  createWorkspace: {
    method: "POST",
    path: taskctlApiRoutes.workspaces,
    authorization: "human-organization",
    session: false,
    idempotency: true,
    requestSchema: createWorkspaceRequestSchema,
    responseSchema: createWorkspaceEnvelopeSchema,
  },
  createAgent: {
    method: "POST",
    path: taskctlApiRoutes.agents,
    authorization: "human-organization",
    session: false,
    idempotency: true,
    requestSchema: createAgentRequestSchema,
    responseSchema: createAgentEnvelopeSchema,
  },
  listAgents: {
    method: "GET",
    path: taskctlApiRoutes.agents,
    authorization: "human-organization",
    session: false,
    idempotency: false,
    querySchema: listAgentsQuerySchema,
    responseSchema: listAgentsEnvelopeSchema,
  },
  getAgent: {
    method: "GET",
    path: taskctlApiRoutes.agent,
    pathParamsSchema: agentRouteParamsSchema,
    authorization: "human-organization",
    session: false,
    idempotency: false,
    querySchema: getAgentQuerySchema,
    responseSchema: getAgentEnvelopeSchema,
  },
  createAgentEnrollment: {
    method: "POST",
    path: taskctlApiRoutes.agentEnrollments,
    pathParamsSchema: agentRouteParamsSchema,
    authorization: "human-organization",
    session: false,
    idempotency: true,
    requestSchema: createAgentEnrollmentRequestSchema,
    responseSchema: createAgentEnrollmentEnvelopeSchema,
  },
  listAgentCredentials: {
    method: "GET",
    path: taskctlApiRoutes.agentCredentials,
    pathParamsSchema: agentRouteParamsSchema,
    authorization: "human-organization",
    session: false,
    idempotency: false,
    querySchema: listAgentCredentialsQuerySchema,
    responseSchema: listAgentCredentialsEnvelopeSchema,
  },
  revokeAgentCredential: {
    method: "POST",
    path: taskctlApiRoutes.agentCredentialRevoke,
    pathParamsSchema: agentCredentialRouteParamsSchema,
    authorization: "human-organization",
    session: false,
    idempotency: true,
    requestSchema: revokeAgentCredentialRequestSchema,
    responseSchema: revokeAgentCredentialEnvelopeSchema,
  },
  listAgentSessions: {
    method: "GET",
    path: taskctlApiRoutes.agentSessions,
    pathParamsSchema: agentRouteParamsSchema,
    authorization: "human-organization",
    session: false,
    idempotency: false,
    querySchema: listAgentSessionsQuerySchema,
    responseSchema: listAgentSessionsEnvelopeSchema,
  },
  disableAgent: {
    method: "POST",
    path: taskctlApiRoutes.agentDisable,
    pathParamsSchema: agentRouteParamsSchema,
    authorization: "human-organization",
    session: false,
    idempotency: true,
    requestSchema: disableAgentRequestSchema,
    responseSchema: disableAgentEnvelopeSchema,
  },
  redeemEnrollment: {
    method: "POST",
    path: taskctlApiRoutes.redeemEnrollment,
    authorization: "enrollment",
    session: false,
    idempotency: true,
    requestSchema: redeemEnrollmentRequestSchema,
    responseSchema: redeemEnrollmentEnvelopeSchema,
  },
  startSession: {
    method: "POST",
    path: taskctlApiRoutes.sessions,
    authorization: "agent",
    session: false,
    idempotency: true,
    requestSchema: startSessionRequestSchema,
    responseSchema: startSessionEnvelopeSchema,
  },
  context: {
    method: "GET",
    path: taskctlApiRoutes.context,
    authorization: "agent",
    session: true,
    idempotency: false,
    responseSchema: contextEnvelopeSchema,
  },
  createTask: {
    method: "POST",
    path: taskctlApiRoutes.tasks,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: createTaskRequestSchema,
    responseSchema: createTaskEnvelopeSchema,
  },
  readyTasks: {
    method: "GET",
    path: taskctlApiRoutes.readyTasks,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: readyTasksQuerySchema,
    responseSchema: readyTasksEnvelopeSchema,
  },
  claimTask: {
    method: "POST",
    path: taskctlApiRoutes.claimTask,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: claimTaskRequestSchema,
    responseSchema: claimTaskEnvelopeSchema,
  },
  renewClaim: {
    method: "POST",
    path: taskctlApiRoutes.renewClaim,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: renewClaimRequestSchema,
    responseSchema: renewClaimEnvelopeSchema,
  },
  releaseClaim: {
    method: "POST",
    path: taskctlApiRoutes.releaseClaim,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: releaseClaimRequestSchema,
    responseSchema: releaseClaimEnvelopeSchema,
  },
  listTasks: {
    method: "GET",
    path: taskctlApiRoutes.tasks,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: listTasksQuerySchema,
    responseSchema: listTasksEnvelopeSchema,
  },
  getTask: {
    method: "GET",
    path: taskctlApiRoutes.task,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: false,
    responseSchema: getTaskEnvelopeSchema,
  },
  blockedTasks: {
    method: "GET",
    path: taskctlApiRoutes.blockedTasks,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: blockedTasksQuerySchema,
    responseSchema: blockedTasksEnvelopeSchema,
  },
  updateTask: {
    method: "POST",
    path: taskctlApiRoutes.taskUpdate,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: updateTaskRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  cancelTask: {
    method: "POST",
    path: taskctlApiRoutes.taskCancel,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "human-workspace",
    session: false,
    idempotency: true,
    requestSchema: cancelTaskRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  reopenTask: {
    method: "POST",
    path: taskctlApiRoutes.taskReopen,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "human-workspace",
    session: false,
    idempotency: true,
    requestSchema: reopenTaskRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  assignTask: {
    method: "POST",
    path: taskctlApiRoutes.taskAssign,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: assignTaskRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  deferTask: {
    method: "POST",
    path: taskctlApiRoutes.taskDefer,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: deferTaskRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  listTaskLabels: {
    method: "GET",
    path: taskctlApiRoutes.taskLabels,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: false,
    responseSchema: listTaskLabelsEnvelopeSchema,
  },
  addTaskLabel: {
    method: "POST",
    path: taskctlApiRoutes.taskLabels,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: taskLabelMutationRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  removeTaskLabel: {
    method: "POST",
    path: taskctlApiRoutes.taskLabelRemove,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: taskLabelMutationRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  listTaskComments: {
    method: "GET",
    path: taskctlApiRoutes.taskComments,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: listTaskCommentsQuerySchema,
    responseSchema: listTaskCommentsEnvelopeSchema,
  },
  addTaskComment: {
    method: "POST",
    path: taskctlApiRoutes.taskComments,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: addTaskCommentRequestSchema,
    responseSchema: addTaskCommentEnvelopeSchema,
  },
  listTaskEvents: {
    method: "GET",
    path: taskctlApiRoutes.taskEvents,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: listTaskEventsQuerySchema,
    responseSchema: listTaskEventsEnvelopeSchema,
  },
  taskGraph: {
    method: "GET",
    path: taskctlApiRoutes.taskGraph,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: taskGraphQuerySchema,
    responseSchema: taskGraphEnvelopeSchema,
  },
  listTaskDependencies: {
    method: "GET",
    path: taskctlApiRoutes.taskDependencies,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: listTaskDependenciesQuerySchema,
    responseSchema: listTaskDependenciesEnvelopeSchema,
  },
  addTaskDependency: {
    method: "POST",
    path: taskctlApiRoutes.taskDependencies,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: taskDependencyMutationRequestSchema,
    responseSchema: taskDependencyMutationEnvelopeSchema,
  },
  removeTaskDependency: {
    method: "POST",
    path: taskctlApiRoutes.taskDependencyRemove,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: taskDependencyMutationRequestSchema,
    responseSchema: taskDependencyMutationEnvelopeSchema,
  },
  setTaskParent: {
    method: "POST",
    path: taskctlApiRoutes.taskParentSet,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: setTaskParentRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  clearTaskParent: {
    method: "POST",
    path: taskctlApiRoutes.taskParentClear,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: clearTaskParentRequestSchema,
    responseSchema: taskMutationEnvelopeSchema,
  },
  listWorkspaceRepositories: {
    method: "GET",
    path: taskctlApiRoutes.workspaceRepositories,
    authorization: "human-workspace",
    session: false,
    idempotency: false,
    querySchema: listWorkspaceRepositoriesQuerySchema,
    responseSchema: listWorkspaceRepositoriesEnvelopeSchema,
  },
  createWorkspaceRepository: {
    method: "POST",
    path: taskctlApiRoutes.workspaceRepositories,
    authorization: "human-workspace",
    session: false,
    idempotency: true,
    requestSchema: createWorkspaceRepositoryRequestSchema,
    responseSchema: workspaceRepositoryEnvelopeSchema,
  },
  removeWorkspaceRepository: {
    method: "POST",
    path: taskctlApiRoutes.workspaceRepositoryRemove,
    pathParamsSchema: repositoryRouteParamsSchema,
    authorization: "human-workspace",
    session: false,
    idempotency: true,
    requestSchema: removeWorkspaceRepositoryRequestSchema,
    responseSchema: removeWorkspaceRepositoryEnvelopeSchema,
  },
  listTaskReferences: {
    method: "GET",
    path: taskctlApiRoutes.taskReferences,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: listTaskReferencesQuerySchema,
    responseSchema: listTaskReferencesEnvelopeSchema,
  },
  addTaskReference: {
    method: "POST",
    path: taskctlApiRoutes.taskReferences,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: addTaskReferenceRequestSchema,
    responseSchema: taskReferenceEnvelopeSchema,
  },
  removeTaskReference: {
    method: "POST",
    path: taskctlApiRoutes.taskReferenceRemove,
    pathParamsSchema: taskReferenceRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: removeTaskReferenceRequestSchema,
    responseSchema: removeTaskReferenceEnvelopeSchema,
  },
  submitTask: {
    method: "POST",
    path: taskctlApiRoutes.submitTask,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: submitTaskRequestSchema,
    responseSchema: submitTaskEnvelopeSchema,
  },
  reviewQueue: {
    method: "GET",
    path: taskctlApiRoutes.reviews,
    authorization: "agent",
    session: true,
    idempotency: false,
    querySchema: reviewQueueQuerySchema,
    responseSchema: reviewQueueEnvelopeSchema,
  },
  acceptTask: {
    method: "POST",
    path: taskctlApiRoutes.acceptTask,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: acceptTaskRequestSchema,
    responseSchema: acceptTaskEnvelopeSchema,
  },
  rejectTask: {
    method: "POST",
    path: taskctlApiRoutes.rejectTask,
    pathParamsSchema: taskRouteParamsSchema,
    authorization: "agent",
    session: true,
    idempotency: true,
    requestSchema: rejectTaskRequestSchema,
    responseSchema: rejectTaskEnvelopeSchema,
  },
} as const;
