// Frozen canonical Work tables/indexes emitted by exact main7ab347813f8d7e4f31e9584752c801dd1ca0cda0.
// Source Work-store SHA2560b79503811b93ce56171f5cdcb1d5d840e7e6c005068b579f3f1a8637eee2146.
// Matched against the authentic canonical49 public-API capture; no current
// provider registry, canonical-profile foundation, or runtime defaults enter.
// Migration installers use CREATE IF NOT EXISTS and never rebuild old tables,
// preserving the exact original ALTER column placement on admitted histories.
export const CANONICAL_WORK_CORE_DEFINITIONS = Object.freeze([
  Object.freeze(["table","work_clock","CREATE TABLE IF NOT EXISTS work_clock (\n  singleton INTEGER PRIMARY KEY CHECK(singleton = 1),\n  logical_time INTEGER NOT NULL CHECK(logical_time >= 0)\n) STRICT;"] as const),
  Object.freeze(["table","work_purge_authority","CREATE TABLE IF NOT EXISTS work_purge_authority (\n  singleton INTEGER PRIMARY KEY CHECK(singleton=1),\n  work_id TEXT NOT NULL UNIQUE CHECK(length(work_id) BETWEEN 6 AND 80),\n  idempotency_key TEXT NOT NULL UNIQUE CHECK(length(idempotency_key)=36),\n  created_at INTEGER NOT NULL CHECK(created_at>=0)\n) STRICT;"] as const),
  Object.freeze(["table","work_release_tombstones","CREATE TABLE IF NOT EXISTS work_release_tombstones (\n  work_id TEXT PRIMARY KEY CHECK(length(work_id) BETWEEN 6 AND 80),\n  release_idempotency_key TEXT NOT NULL UNIQUE CHECK(length(release_idempotency_key)=36),\n  release_request_digest TEXT NOT NULL CHECK(length(release_request_digest)=64 AND release_request_digest NOT GLOB '*[^0-9a-f]*'),\n  client_ref_digest TEXT NOT NULL UNIQUE CHECK(length(client_ref_digest)=64 AND client_ref_digest NOT GLOB '*[^0-9a-f]*'),\n  coordinator_session_id TEXT NOT NULL CHECK(length(coordinator_session_id) BETWEEN 6 AND 80),\n  terminal_kind TEXT NOT NULL CHECK(terminal_kind IN ('work.complete','work.fail','work.cancel')),\n  terminal_request_digest TEXT NOT NULL CHECK(length(terminal_request_digest)=64 AND terminal_request_digest NOT GLOB '*[^0-9a-f]*'),\n  final_revision INTEGER NOT NULL CHECK(final_revision>0),\n  final_head_hash TEXT NOT NULL CHECK(length(final_head_hash)=64 AND final_head_hash NOT GLOB '*[^0-9a-f]*'),\n  discarded_counts_json TEXT NOT NULL CHECK(json_valid(discarded_counts_json) AND length(CAST(discarded_counts_json AS BLOB))<=4096),\n  discarded_records_digest TEXT NOT NULL CHECK(length(discarded_records_digest)=64 AND discarded_records_digest NOT GLOB '*[^0-9a-f]*'),\n  released_at INTEGER NOT NULL CHECK(released_at>=0),\n  retention_upper_bound_at INTEGER NOT NULL CHECK(retention_upper_bound_at>=released_at),\n  result_json TEXT NOT NULL CHECK(json_valid(result_json) AND length(CAST(result_json AS BLOB))<=65536)\n) STRICT;"] as const),
  Object.freeze(["index","work_release_tombstones_retention","CREATE INDEX IF NOT EXISTS work_release_tombstones_retention\n  ON work_release_tombstones(released_at,work_id);"] as const),
  Object.freeze(["table","works","CREATE TABLE IF NOT EXISTS works (\n  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 6 AND 80),\n  client_ref TEXT NOT NULL UNIQUE CHECK(length(CAST(client_ref AS BLOB)) BETWEEN 1 AND 256),\n  coordinator_session_id TEXT NOT NULL REFERENCES sessions(id),\n  objective TEXT NOT NULL CHECK(length(CAST(objective AS BLOB)) BETWEEN 1 AND 16384),\n  preset_contract INTEGER NOT NULL DEFAULT 1 CHECK(preset_contract IN (1,2)),\n  state TEXT NOT NULL CHECK(state IN ('active','cancel_pending','fail_pending','completed','failed','cancelled')),\n  revision INTEGER NOT NULL CHECK(revision >= 0),\n  stream_epoch TEXT NOT NULL CHECK(length(stream_epoch) = 36),\n  next_sequence INTEGER NOT NULL CHECK(next_sequence > 0),\n  head_hash TEXT CHECK(head_hash IS NULL OR (length(head_hash) = 64 AND head_hash NOT GLOB '*[^0-9a-f]*')),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  updated_at INTEGER NOT NULL CHECK(updated_at >= created_at),\n  CHECK((next_sequence = 1 AND head_hash IS NULL) OR (next_sequence > 1 AND head_hash IS NOT NULL))\n) STRICT;"] as const),
  Object.freeze(["table","work_routes","CREATE TABLE IF NOT EXISTS work_routes (\n  work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,\n  ordinal INTEGER NOT NULL CHECK(ordinal >= 0 AND ordinal < 64),\n  account_id TEXT NOT NULL REFERENCES profiles(id),\n  project_id TEXT NOT NULL REFERENCES projects(id),\n  preset TEXT NOT NULL CHECK(preset IN ('low','high','ultra')),\n  fast INTEGER NOT NULL CHECK(fast IN (0,1)),\n  PRIMARY KEY(work_id,account_id,project_id,preset,fast),\n  UNIQUE(work_id,ordinal)\n) STRICT;"] as const),
  Object.freeze(["table","work_members","CREATE TABLE IF NOT EXISTS work_members (\n  work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,\n  session_id TEXT NOT NULL REFERENCES sessions(id),\n  joined_at INTEGER NOT NULL CHECK(joined_at >= 0),\n  PRIMARY KEY(work_id,session_id)\n) STRICT;"] as const),
  Object.freeze(["table","work_tasks","CREATE TABLE IF NOT EXISTS work_tasks (\n  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 6 AND 80),\n  work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,\n  client_ref TEXT NOT NULL CHECK(length(CAST(client_ref AS BLOB)) BETWEEN 1 AND 256),\n  ordinal INTEGER NOT NULL CHECK(ordinal >= 0 AND ordinal < 256),\n  parent_task_id TEXT,\n  depth INTEGER NOT NULL CHECK(depth BETWEEN 1 AND 8),\n  objective TEXT NOT NULL CHECK(length(CAST(objective AS BLOB)) BETWEEN 1 AND 16384),\n  instructions TEXT NOT NULL CHECK(length(CAST(instructions AS BLOB)) BETWEEN 1 AND 32768),\n  criteria_json TEXT NOT NULL CHECK(json_valid(criteria_json) AND length(CAST(criteria_json AS BLOB)) <= 32768),\n  account_id TEXT NOT NULL REFERENCES profiles(id),\n  project_id TEXT NOT NULL REFERENCES projects(id),\n  preset TEXT NOT NULL CHECK(preset IN ('low','high','ultra')),\n  fast INTEGER NOT NULL CHECK(fast IN (0,1)),\n  priority INTEGER NOT NULL CHECK(priority BETWEEN -100 AND 100),\n  not_before INTEGER CHECK(not_before IS NULL OR not_before >= 0),\n  claim_by INTEGER CHECK(claim_by IS NULL OR claim_by >= 0),\n  deadline INTEGER CHECK(deadline IS NULL OR deadline >= 0),\n  max_attempts INTEGER NOT NULL CHECK(max_attempts BETWEEN 1 AND 32),\n  required_reviews INTEGER NOT NULL CHECK(required_reviews BETWEEN 0 AND 16),\n  result_kind TEXT NOT NULL CHECK(result_kind IN ('text','json')),\n  min_evidence INTEGER NOT NULL CHECK(min_evidence BETWEEN 0 AND 16),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  UNIQUE(work_id,id),\n  UNIQUE(work_id,client_ref),\n  FOREIGN KEY(work_id,parent_task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,\n  FOREIGN KEY(work_id,account_id,project_id,preset,fast)\n    REFERENCES work_routes(work_id,account_id,project_id,preset,fast) ON DELETE CASCADE,\n  CHECK(parent_task_id IS NULL OR parent_task_id != id),\n  CHECK(claim_by IS NULL OR not_before IS NULL OR claim_by > not_before),\n  CHECK(deadline IS NULL OR not_before IS NULL OR deadline > not_before),\n  CHECK(deadline IS NULL OR claim_by IS NULL OR deadline >= claim_by)\n) STRICT;"] as const),
  Object.freeze(["index","work_tasks_order","CREATE INDEX IF NOT EXISTS work_tasks_order ON work_tasks(work_id,priority DESC,ordinal,id);"] as const),
  Object.freeze(["index","work_tasks_parent","CREATE INDEX IF NOT EXISTS work_tasks_parent ON work_tasks(work_id,parent_task_id,ordinal,id);"] as const),
  Object.freeze(["table","work_task_dependencies","CREATE TABLE IF NOT EXISTS work_task_dependencies (\n  work_id TEXT NOT NULL,\n  task_id TEXT NOT NULL,\n  dependency_task_id TEXT NOT NULL,\n  ordinal INTEGER NOT NULL CHECK(ordinal >= 0 AND ordinal < 16),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  PRIMARY KEY(work_id,task_id,dependency_task_id),\n  UNIQUE(work_id,task_id,ordinal),\n  FOREIGN KEY(work_id,task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE,\n  FOREIGN KEY(work_id,dependency_task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE,\n  CHECK(task_id != dependency_task_id)\n) STRICT;"] as const),
  Object.freeze(["index","work_task_dependencies_reverse","CREATE INDEX IF NOT EXISTS work_task_dependencies_reverse\n  ON work_task_dependencies(work_id,dependency_task_id,task_id);"] as const),
  Object.freeze(["table","work_task_states","CREATE TABLE IF NOT EXISTS work_task_states (\n  task_id TEXT PRIMARY KEY REFERENCES work_tasks(id) ON DELETE CASCADE,\n  work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,\n  state TEXT NOT NULL CHECK(state IN ('pending','claimed','dispatching','running','submitted','completed','failed','recovery_required','cancelled')),\n  revision INTEGER NOT NULL CHECK(revision > 0),\n  next_fence INTEGER NOT NULL CHECK(next_fence > 0),\n  attempt_count INTEGER NOT NULL CHECK(attempt_count >= 0),\n  accepted_submission_id TEXT REFERENCES work_submissions(id) DEFERRABLE INITIALLY DEFERRED,\n  retry_not_before INTEGER CHECK(retry_not_before IS NULL OR retry_not_before >= 0),\n  updated_at INTEGER NOT NULL CHECK(updated_at >= 0),\n  UNIQUE(work_id,task_id),\n  CHECK((state = 'completed' AND accepted_submission_id IS NOT NULL) OR state != 'completed')\n) STRICT;"] as const),
  Object.freeze(["index","work_task_states_ready","CREATE INDEX IF NOT EXISTS work_task_states_ready ON work_task_states(work_id,state,updated_at,task_id);"] as const),
  Object.freeze(["table","work_attempts","CREATE TABLE IF NOT EXISTS work_attempts (\n  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 6 AND 80),\n  work_id TEXT NOT NULL,\n  task_id TEXT NOT NULL,\n  worker_session_id TEXT NOT NULL REFERENCES sessions(id),\n  account_id TEXT NOT NULL REFERENCES profiles(id),\n  project_id TEXT NOT NULL REFERENCES projects(id),\n  preset TEXT NOT NULL CHECK(preset IN ('low','high','ultra')),\n  fast INTEGER NOT NULL CHECK(fast IN (0,1)),\n  fence INTEGER NOT NULL CHECK(fence > 0),\n  revision INTEGER NOT NULL CHECK(revision > 0),\n  state TEXT NOT NULL CHECK(state IN ('claimed','dispatching','running','submitted','completed','blocked','failed','released','expired','recovery_required','cancelled')),\n  lease_expires_at INTEGER NOT NULL CHECK(lease_expires_at >= 0),\n  target_session_id TEXT REFERENCES sessions(id),\n  dispatch_mode TEXT CHECK(dispatch_mode IS NULL OR dispatch_mode='send'),\n  submission_id TEXT REFERENCES work_submissions(id) DEFERRABLE INITIALLY DEFERRED,\n  account_generation INTEGER NOT NULL CHECK(account_generation >= 0),\n  daemon_generation INTEGER NOT NULL CHECK(daemon_generation >= 0),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  updated_at INTEGER NOT NULL CHECK(updated_at >= created_at),\n  terminal_at INTEGER CHECK(terminal_at IS NULL OR terminal_at >= created_at),\n  UNIQUE(task_id,fence),\n  UNIQUE(work_id,id),\n  FOREIGN KEY(work_id,task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE,\n  CHECK((target_session_id IS NULL AND dispatch_mode IS NULL) OR (target_session_id IS NOT NULL AND dispatch_mode IS NOT NULL))\n) STRICT;"] as const),
  Object.freeze(["index","work_attempts_one_live","CREATE UNIQUE INDEX IF NOT EXISTS work_attempts_one_live\n  ON work_attempts(task_id)\n  WHERE state IN ('claimed','dispatching','running','submitted','recovery_required');"] as const),
  Object.freeze(["index","work_attempts_actor","CREATE INDEX IF NOT EXISTS work_attempts_actor ON work_attempts(work_id,worker_session_id,state,updated_at,id);"] as const),
  Object.freeze(["index","work_attempts_lease","CREATE INDEX IF NOT EXISTS work_attempts_lease ON work_attempts(work_id,state,lease_expires_at,id);"] as const),
  Object.freeze(["table","work_attempt_reports","CREATE TABLE IF NOT EXISTS work_attempt_reports (\n  idempotency_key TEXT PRIMARY KEY CHECK(length(idempotency_key) = 36),\n  work_id TEXT NOT NULL,\n  attempt_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK(kind IN ('checkpoint','submit','blocked','failed','unknown')),\n  report_json TEXT NOT NULL CHECK(json_valid(report_json) AND length(CAST(report_json AS BLOB)) <= 2097152),\n  report_digest TEXT NOT NULL CHECK(length(report_digest) = 64 AND report_digest NOT GLOB '*[^0-9a-f]*'),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  FOREIGN KEY(work_id,attempt_id) REFERENCES work_attempts(work_id,id) ON DELETE CASCADE\n) STRICT;"] as const),
  Object.freeze(["index","work_attempt_reports_attempt","CREATE INDEX IF NOT EXISTS work_attempt_reports_attempt ON work_attempt_reports(attempt_id,created_at,idempotency_key);"] as const),
  Object.freeze(["table","work_submissions","CREATE TABLE IF NOT EXISTS work_submissions (\n  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 6 AND 80),\n  work_id TEXT NOT NULL,\n  task_id TEXT NOT NULL,\n  attempt_id TEXT NOT NULL,\n  worker_session_id TEXT NOT NULL REFERENCES sessions(id),\n  summary TEXT NOT NULL CHECK(length(CAST(summary AS BLOB)) BETWEEN 1 AND 16384),\n  result_json TEXT NOT NULL CHECK(json_valid(result_json) AND length(CAST(result_json AS BLOB)) <= 2097152),\n  evidence_json TEXT NOT NULL CHECK(json_valid(evidence_json) AND length(CAST(evidence_json AS BLOB)) <= 2097152),\n  content_digest TEXT NOT NULL CHECK(length(content_digest) = 64 AND content_digest NOT GLOB '*[^0-9a-f]*'),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  UNIQUE(work_id,id),\n  UNIQUE(attempt_id),\n  FOREIGN KEY(work_id,task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE,\n  FOREIGN KEY(work_id,attempt_id) REFERENCES work_attempts(work_id,id) ON DELETE CASCADE\n) STRICT;"] as const),
  Object.freeze(["index","work_submissions_task","CREATE INDEX IF NOT EXISTS work_submissions_task ON work_submissions(task_id,created_at,id);"] as const),
  Object.freeze(["table","work_reviews","CREATE TABLE IF NOT EXISTS work_reviews (\n  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 6 AND 80),\n  work_id TEXT NOT NULL,\n  submission_id TEXT NOT NULL,\n  reviewer_session_id TEXT NOT NULL REFERENCES sessions(id),\n  decision TEXT NOT NULL CHECK(decision IN ('accept','revise','reject')),\n  review_json TEXT NOT NULL CHECK(json_valid(review_json) AND length(CAST(review_json AS BLOB)) <= 2097152),\n  review_digest TEXT NOT NULL CHECK(length(review_digest) = 64 AND review_digest NOT GLOB '*[^0-9a-f]*'),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  UNIQUE(submission_id,reviewer_session_id),\n  UNIQUE(work_id,id),\n  FOREIGN KEY(work_id,submission_id) REFERENCES work_submissions(work_id,id) ON DELETE CASCADE\n) STRICT;"] as const),
  Object.freeze(["index","work_reviews_submission","CREATE INDEX IF NOT EXISTS work_reviews_submission ON work_reviews(submission_id,created_at,id);"] as const),
  Object.freeze(["table","work_signals","CREATE TABLE IF NOT EXISTS work_signals (\n  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 6 AND 80),\n  work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,\n  from_session_id TEXT NOT NULL REFERENCES sessions(id),\n  to_session_id TEXT NOT NULL REFERENCES sessions(id),\n  target_account_generation INTEGER NOT NULL CHECK(target_account_generation >= 0),\n  task_id TEXT,\n  reply_to_signal_id TEXT,\n  mode TEXT NOT NULL CHECK(mode IN ('queue','steer')),\n  body TEXT NOT NULL CHECK(length(CAST(body AS BLOB)) BETWEEN 1 AND 32768),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  UNIQUE(work_id,id),\n  FOREIGN KEY(work_id,task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE,\n  FOREIGN KEY(work_id,reply_to_signal_id) REFERENCES work_signals(work_id,id) ON DELETE CASCADE\n) STRICT;"] as const),
  Object.freeze(["index","work_signals_recipient","CREATE INDEX IF NOT EXISTS work_signals_recipient ON work_signals(work_id,to_session_id,created_at,id);"] as const),
  Object.freeze(["table","work_task_history_index","CREATE TABLE IF NOT EXISTS work_task_history_index (\n  ordinal INTEGER PRIMARY KEY AUTOINCREMENT CHECK(ordinal > 0 AND ordinal <= 9007199254740991),\n  work_id TEXT NOT NULL,\n  task_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK(kind IN ('attempt','attempt_report','submission','review','signal')),\n  stable_key TEXT NOT NULL CHECK(length(CAST(stable_key AS BLOB)) BETWEEN 6 AND 80),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  UNIQUE(kind,stable_key),\n  FOREIGN KEY(work_id,task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE\n) STRICT;"] as const),
  Object.freeze(["index","work_task_history_index_page","CREATE INDEX IF NOT EXISTS work_task_history_index_page\n  ON work_task_history_index(work_id,task_id,ordinal DESC);"] as const),
  Object.freeze(["table","work_task_history_versions","CREATE TABLE IF NOT EXISTS work_task_history_versions (\n  ordinal INTEGER PRIMARY KEY AUTOINCREMENT CHECK(ordinal > 0 AND ordinal <= 9007199254740991),\n  history_ordinal INTEGER NOT NULL REFERENCES work_task_history_index(ordinal) ON DELETE CASCADE,\n  work_id TEXT NOT NULL,\n  task_id TEXT NOT NULL,\n  event_sequence INTEGER NOT NULL CHECK(event_sequence > 0),\n  record_json TEXT NOT NULL CHECK(\n    json_valid(record_json)\n    AND length(CAST(record_json AS BLOB)) <= 2097152\n  ),\n  record_digest TEXT NOT NULL CHECK(\n    length(record_digest)=64 AND record_digest NOT GLOB '*[^0-9a-f]*'\n  ),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  UNIQUE(history_ordinal,event_sequence),\n  FOREIGN KEY(work_id,task_id) REFERENCES work_tasks(work_id,id) ON DELETE CASCADE,\n  FOREIGN KEY(work_id,event_sequence) REFERENCES work_events(work_id,sequence)\n    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED\n) STRICT;"] as const),
  Object.freeze(["index","work_task_history_versions_cut","CREATE INDEX IF NOT EXISTS work_task_history_versions_cut\n  ON work_task_history_versions(history_ordinal,event_sequence DESC,ordinal DESC);"] as const),
  Object.freeze(["index","work_task_history_versions_work","CREATE INDEX IF NOT EXISTS work_task_history_versions_work\n  ON work_task_history_versions(work_id,task_id,ordinal);"] as const),
  Object.freeze(["table","work_signal_receipts","CREATE TABLE IF NOT EXISTS work_signal_receipts (\n  signal_id TEXT NOT NULL REFERENCES work_signals(id) ON DELETE CASCADE,\n  sequence INTEGER NOT NULL CHECK(sequence > 0),\n  kind TEXT NOT NULL CHECK(kind IN ('accepted','ack','unknown','failed')),\n  actor_session_id TEXT REFERENCES sessions(id),\n  detail_code TEXT CHECK(detail_code IS NULL OR length(CAST(detail_code AS BLOB)) BETWEEN 1 AND 120),\n  recorded_at INTEGER NOT NULL CHECK(recorded_at >= 0),\n  PRIMARY KEY(signal_id,sequence)\n) STRICT;"] as const),
  Object.freeze(["index","work_signal_receipts_kind","CREATE INDEX IF NOT EXISTS work_signal_receipts_kind ON work_signal_receipts(signal_id,kind,sequence);"] as const),
  Object.freeze(["table","work_events","CREATE TABLE IF NOT EXISTS work_events (\n  work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,\n  sequence INTEGER NOT NULL CHECK(sequence > 0),\n  revision INTEGER NOT NULL CHECK(revision > 0),\n  stream_epoch TEXT NOT NULL CHECK(length(stream_epoch) = 36),\n  kind TEXT NOT NULL CHECK(length(CAST(kind AS BLOB)) BETWEEN 1 AND 120),\n  actor_session_id TEXT REFERENCES sessions(id),\n  payload_json TEXT NOT NULL CHECK(json_valid(payload_json) AND length(CAST(payload_json AS BLOB)) <= 131072),\n  payload_digest TEXT NOT NULL CHECK(length(payload_digest) = 64 AND payload_digest NOT GLOB '*[^0-9a-f]*'),\n  previous_hash TEXT CHECK(previous_hash IS NULL OR (length(previous_hash) = 64 AND previous_hash NOT GLOB '*[^0-9a-f]*')),\n  event_hash TEXT NOT NULL CHECK(length(event_hash) = 64 AND event_hash NOT GLOB '*[^0-9a-f]*'),\n  daemon_generation INTEGER NOT NULL CHECK(daemon_generation >= 0),\n  recorded_at INTEGER NOT NULL CHECK(recorded_at >= 0),\n  PRIMARY KEY(work_id,sequence),\n  UNIQUE(work_id,revision),\n  UNIQUE(work_id,event_hash),\n  CHECK((sequence = 1 AND previous_hash IS NULL) OR (sequence > 1 AND previous_hash IS NOT NULL))\n) STRICT;"] as const),
  Object.freeze(["index","work_events_revision","CREATE INDEX IF NOT EXISTS work_events_revision ON work_events(work_id,revision);"] as const),
  Object.freeze(["table","work_idempotency_intents","CREATE TABLE IF NOT EXISTS work_idempotency_intents (\n  idempotency_key TEXT PRIMARY KEY CHECK(length(idempotency_key) = 36),\n  operation_kind TEXT NOT NULL CHECK(length(CAST(operation_kind AS BLOB)) BETWEEN 1 AND 120),\n  work_id TEXT REFERENCES works(id) ON DELETE CASCADE,\n  request_digest TEXT NOT NULL CHECK(length(request_digest) = 64 AND request_digest NOT GLOB '*[^0-9a-f]*'),\n  result_json TEXT NOT NULL CHECK(json_valid(result_json) AND length(CAST(result_json AS BLOB)) <= 2097152),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0)\n) STRICT;"] as const),
  Object.freeze(["index","work_idempotency_work","CREATE INDEX IF NOT EXISTS work_idempotency_work ON work_idempotency_intents(work_id,created_at,idempotency_key);"] as const),
  Object.freeze(["table","work_terminal_requests","CREATE TABLE IF NOT EXISTS work_terminal_requests (\n  work_id TEXT PRIMARY KEY REFERENCES works(id) ON DELETE CASCADE,\n  idempotency_key TEXT NOT NULL UNIQUE CHECK(length(idempotency_key)=36),\n  kind TEXT NOT NULL CHECK(kind IN ('work.complete','work.fail','work.cancel')),\n  state TEXT NOT NULL CHECK(state IN ('requested','settled')),\n  actor_session_id TEXT NOT NULL REFERENCES sessions(id),\n  summary TEXT NOT NULL CHECK(length(CAST(summary AS BLOB)) BETWEEN 1 AND 16384),\n  result_json TEXT CHECK(result_json IS NULL OR (\n    json_valid(result_json) AND length(CAST(result_json AS BLOB))<=2097152\n  )),\n  evidence_json TEXT NOT NULL CHECK(json_valid(evidence_json) AND length(CAST(evidence_json AS BLOB))<=2097152),\n  request_digest TEXT NOT NULL CHECK(length(request_digest)=64 AND request_digest NOT GLOB '*[^0-9a-f]*'),\n  requested_at INTEGER NOT NULL CHECK(requested_at>=0),\n  settled_at INTEGER CHECK(settled_at IS NULL OR settled_at>=requested_at),\n  CHECK((state='requested' AND settled_at IS NULL) OR (state='settled' AND settled_at IS NOT NULL)),\n  CHECK((kind='work.complete' AND (result_json IS NULL OR json_valid(result_json)))\n     OR (kind!='work.complete' AND result_json IS NULL))\n) STRICT;"] as const),
  Object.freeze(["table","work_prepared_effects","CREATE TABLE IF NOT EXISTS work_prepared_effects (\n  idempotency_key TEXT PRIMARY KEY REFERENCES work_idempotency_intents(idempotency_key) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,\n  work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,\n  effect_kind TEXT NOT NULL CHECK(effect_kind IN ('attempt_dispatch','signal_send')),\n  subject_id TEXT NOT NULL CHECK(length(subject_id) BETWEEN 6 AND 80),\n  instruction_json TEXT NOT NULL CHECK(json_valid(instruction_json) AND length(CAST(instruction_json AS BLOB)) <= 2097152),\n  instruction_digest TEXT NOT NULL CHECK(length(instruction_digest) = 64 AND instruction_digest NOT GLOB '*[^0-9a-f]*'),\n  daemon_generation INTEGER NOT NULL CHECK(daemon_generation >= 0),\n  state TEXT NOT NULL CHECK(state IN ('prepared','effect_started','accepted','failed','unknown')),\n  outcome_digest TEXT CHECK(outcome_digest IS NULL OR (length(outcome_digest) = 64 AND outcome_digest NOT GLOB '*[^0-9a-f]*')),\n  outcome_json TEXT CHECK(outcome_json IS NULL OR (json_valid(outcome_json) AND length(CAST(outcome_json AS BLOB)) <= 65536)),\n  prepared_at INTEGER NOT NULL CHECK(prepared_at >= 0),\n  finalized_at INTEGER CHECK(finalized_at IS NULL OR finalized_at >= prepared_at),\n  CHECK((state IN ('prepared','effect_started') AND outcome_digest IS NULL AND outcome_json IS NULL AND finalized_at IS NULL)\n     OR (state NOT IN ('prepared','effect_started') AND outcome_digest IS NOT NULL AND outcome_json IS NOT NULL AND finalized_at IS NOT NULL))\n) STRICT;"] as const),
  Object.freeze(["index","work_effect_subject_unique","CREATE UNIQUE INDEX IF NOT EXISTS work_effect_subject_unique\n  ON work_prepared_effects(effect_kind,subject_id);"] as const),
  Object.freeze(["index","work_prepared_effects_pending","CREATE INDEX IF NOT EXISTS work_prepared_effects_pending ON work_prepared_effects(prepared_at,idempotency_key)\n  WHERE state IN ('prepared','effect_started');"] as const),
  Object.freeze(["table","work_effect_resolutions","CREATE TABLE IF NOT EXISTS work_effect_resolutions (\n  effect_idempotency_key TEXT PRIMARY KEY REFERENCES work_prepared_effects(idempotency_key) ON DELETE CASCADE,\n  work_id TEXT NOT NULL,\n  attempt_id TEXT NOT NULL,\n  instruction_digest TEXT NOT NULL CHECK(length(instruction_digest) = 64 AND instruction_digest NOT GLOB '*[^0-9a-f]*'),\n  outcome TEXT NOT NULL CHECK(outcome IN ('proven_applied','no_effect','failed')),\n  evidence_digest TEXT NOT NULL CHECK(length(evidence_digest) = 64 AND evidence_digest NOT GLOB '*[^0-9a-f]*'),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0),\n  FOREIGN KEY(work_id,attempt_id) REFERENCES work_attempts(work_id,id) ON DELETE CASCADE\n) STRICT;"] as const),
  Object.freeze(["table","work_nested_effect_settlements","CREATE TABLE IF NOT EXISTS work_nested_effect_settlements (\n  effect_idempotency_key TEXT PRIMARY KEY REFERENCES work_prepared_effects(idempotency_key) ON DELETE CASCADE,\n  nested_mutation_key TEXT NOT NULL UNIQUE CHECK(length(nested_mutation_key) = 36),\n  outcome TEXT NOT NULL CHECK(outcome IN ('accepted','failed')),\n  receipt_json TEXT CHECK(receipt_json IS NULL OR (json_valid(receipt_json) AND length(CAST(receipt_json AS BLOB)) <= 65536)),\n  receipt_digest TEXT NOT NULL CHECK(length(receipt_digest) = 64 AND receipt_digest NOT GLOB '*[^0-9a-f]*'),\n  created_at INTEGER NOT NULL CHECK(created_at >= 0)\n) STRICT;"] as const),
]);

export const CANONICAL_WORK_CLOCK_SEED_SQL =
  "INSERT OR IGNORE INTO work_clock(singleton,logical_time) VALUES (1,0);";
