import * as stylex from "@stylexjs/stylex";

export const sessionScreenStyles = stylex.create({
  choice: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    fontSize: "0.875rem",
    width: "100%",
    justifyContent: "space-between",
    lineHeight: "1.25rem",
    minHeight: "2.75rem",
    paddingBottom: 0,
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: 0,
    textAlign: "start",
    ":disabled": { cursor: "not-allowed", opacity: 0.5 },
  },
  choiceIdle: {
    borderColor: "var(--color-line)",
    color: "var(--color-ink)",
  },
  choiceSelected: {
    borderColor: "var(--color-accent)",
    color: "var(--color-accent)",
  },
  composer: {
    backgroundColor: "var(--color-surface)",
    borderTopColor: "var(--color-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    paddingBottom: "calc(0.75rem + env(safe-area-inset-bottom))",
    paddingLeft: "max(1rem, env(safe-area-inset-left))",
    paddingRight: "max(1rem, env(safe-area-inset-right))",
    paddingTop: "0.75rem",
  },
  danger: {
    color: "var(--color-danger)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  dragActive: {
    outlineColor: "var(--color-accent)",
    outlineOffset: "2px",
    outlineStyle: "solid",
    outlineWidth: "2px",
  },
  fileInput: { display: "none" },
  form: {
    alignItems: "flex-end",
    borderRadius: "0.375rem",
    display: "flex",
    gap: "0.5rem",
  },
  header: {
    alignItems: "center",
    borderBottomColor: "var(--color-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "0.5rem",
    paddingBottom: "0.5rem",
    paddingLeft: "max(0.5rem, env(safe-area-inset-left))",
    paddingRight: "max(0.5rem, env(safe-area-inset-right))",
    paddingTop: "0.5rem",
  },
  heading: {
    fontFamily: "var(--font-sans)",
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  headingSpaced: { marginTop: "1rem" },
  menuDescription: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.25rem",
    overflowWrap: "normal",
  },
  menuOptions: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginTop: "0.5rem",
  },
  quiet: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  quietBody: {
    color: "var(--color-ink-muted)",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  root: {
    height: "100dvh",
    display: "flex",
    flexDirection: "column",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "48rem",
    paddingTop: "env(safe-area-inset-top)",
    width: "100%",
  },
  scroller: {
    flex: 1,
    overflowY: "auto",
    paddingBottom: "1rem",
    paddingLeft: "max(1rem, env(safe-area-inset-left))",
    paddingRight: "max(1rem, env(safe-area-inset-right))",
    paddingTop: "1rem",
  },
  status: { marginTop: "0.5rem" },
  titleBlock: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  title: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
