import * as stylex from "@stylexjs/stylex";

export const settingsScreenStyles = stylex.create({
  danger: {
    color: "var(--color-danger)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  growInput: { flex: 1 },
  header: {
    alignItems: "center",
    backgroundColor: "var(--color-surface)",
    borderBottomColor: "var(--color-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "0.5rem",
    top: 0,
    paddingBottom: "0.75rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    paddingTop: "0.75rem",
    position: "sticky",
    zIndex: 10,
  },
  inlineRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  main: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: "1.5rem",
    paddingBottom: "calc(1rem + env(safe-area-inset-bottom))",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    paddingTop: "1rem",
  },
  attention: {
    color: "var(--color-attention)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  quiet: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  root: {
    display: "flex",
    flexDirection: "column",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "48rem",
    minHeight: "100dvh",
    paddingTop: "env(safe-area-inset-top)",
    width: "100%",
  },
  timeZoneInput: {
    flex: 1,
    minWidth: "10rem",
  },
  title: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
});
